### ISSUE TITLE
PAL audio - right channel filter working better than left...

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#100]
When looking at the output from ld-decode (from PAL discs with analogue audio) it's clear that the right channel is far less noisy than the left.  It's possible that the left channel filter is (in some way) not as correct as the right.

![audacity_clip](https://user-images.githubusercontent.com/1068814/50775714-35979900-1297-11e9-81f8-f08635497713.png)

**Comment by happycube** [comment]
Hopefully will get a chance to look at it this week, with PAL GGV on it's way to Simon

**Comment by happycube** [comment]
Interestingly they pretty much match (albeit with a 2% intensity difference) on ggv1011's 1khz/100% signal.  

What this *really* applies to is audio dropouts, the left channel's are much more intense for some reason.

**Comment by atsampson** [comment]
I tried extracting the analogue audio from a badly-rotted copy of BBCL 7044 [using GNU Radio instead](https://github.com/atsampson/ld-decode-testsuite/blob/master/efm/laserdisc.grc) ([screenshot](https://stuff.offog.org/ld/gnuradio/grc.png)), and the "ticks" in the audio tracks are much less severe. Zoom in to see the detail:

![clicks](https://user-images.githubusercontent.com/436317/67567548-a0786a80-f719-11e9-89e8-a55db8fd1c0e.png)

So it looks like this might indeed be a filter artefact...

**Comment by happycube** [comment]
This should be greatly reduced in rev6 head.

**Comment by simoninns** [comment]
I think this issue can be closed as fixed now - anything else is pretty much covered elsewhere
