### ISSUE TITLE
Maintaining isFirstField order when dropping frames

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#103]
It's important for the down-stream tools to have a trustworthy isFirstField sequence (otherwise fields can be combined into frames incorrectly).

ld-decode should (if all else fails) create a dummy field when one is dropped and mark the JSON with '-1' in the appropriate fields to show the field is invalid.

**Comment by simoninns** [comment]
Partial fix added (now maintains field order, but doesn't correct resulting .tbc video output).  Assigning this issue to @happycube  so he remembers to update it :)

**Comment by happycube** [comment]
Moving to rev5 - the partial fix is good for rev4

**Comment by simoninns** [comment]
@happycube - Is this issue fixed and just not closed?  Haven't seen the issue pop up for a while :)

**Comment by happycube** [comment]
For rev5.2, the previous field of the same type will be repeated.  For rev6 this will be replaced by a totally blank field.

**Comment by simoninns** [comment]
repeating a field will also repeat the VBI; care should be taken to test the VBI processes after the 5.2 temporary fix

**Comment by simoninns** [comment]
This has been mitigated by the work on ld-discmap which can now spot and correct such issues.  Closing this issue
