### ISSUE TITLE
Better support for NTSC pull-down

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#104]
The tool-chain needs to provide intelligent support for discs containing NTSC pull-down frames; this is just a general place-holder for the work.

**Comment by Gamnn** [comment]
An option to switch to intra-field dropout correction might be a good idea, which going forward would still be good to have on improperly pulled-down field-blended material, which I've found far outnumbers material than can be properly reversed.

**Comment by simoninns** [comment]
ld-dropout-correct should now process NTSC pull-down sources correctly with the --intra option.  ld-combine is still 'to be fixed'

**Comment by simoninns** [comment]
As a note: A tool should be created to add pull-down field markers into the JSON metadata.  Then the tools could be enhanced to use the metadata when making decisions (especially inter-frame DOC and 3D comb filtering)

**Comment by simoninns** [comment]
After a lot of experimentation with ld-discmap; the conclusion is that, the only useful implementation of a pull-down frame detector, would need to use field based image comparison to spot the pull-downs (as there is not reliable way to do this with metadata).  This only affected NTSC CAV discs - NTSC CLV pull-down discs have metadata for the pull-down locations and are now handled by ld-discmap successfully.

**Comment by Gamnn** [comment]
Until the toolchain can handle NTSC CAV with unnumbered pull-down frames better, an option in ld-discmap to number all of the non-leadin/leadout frames sequentially would be useful for making the TBCs usable with ld-diffdod/ld-combine.

**Comment by simoninns** [comment]
Fixed - Documentation is here: https://github.com/happycube/ld-decode/wiki/Working-with-multiple-discs
