### ISSUE TITLE
ld-comb-ntsc colors blow out

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#113]
I think it might be best to revert to 100% white level as the default, and add a 75% as an option.

Ralf comparison: http://www.framecompare.com/image-compare/screenshotcomparison/1BJ1NNNU
Current default causes detail to be lost in bright areas.

**Comment by simoninns** [comment]
Fixed; also turned down the colour saturation compensation a little.  Please retest and open another issue if problems are observed.
