### ISSUE TITLE
Dropout in colorburst causes misalignment

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#115]
A dropout in the colorburst can cause the phase to shift out of alignment.

Examples:
![frame_ntsc_source_1129_predoc](https://user-images.githubusercontent.com/44366267/51098523-2c19ae00-180e-11e9-9271-a79ed024f755.png)
![frame_ntsc_source_1129](https://user-images.githubusercontent.com/44366267/51098524-2cb24480-180e-11e9-9209-0c97fb4a9236.png)

![frame_ntsc_source_24_predoc](https://user-images.githubusercontent.com/44366267/51098815-481e4f00-1810-11e9-9081-22880c3f1b83.png)
![frame_ntsc_source_24](https://user-images.githubusercontent.com/44366267/51098816-481e4f00-1810-11e9-9211-57b89c5935c3.png)

**Comment by happycube** [comment]
@Gamnn - I think I've fixed this in rev5 - can you check on your end and close if you agree?

**Comment by happycube** [comment]
(actually, don't.  i realized i fixed the wrong thing ;) )
