### ISSUE TITLE
Implement FLAC in ld-decode for seeking

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#116]
Using ffmpeg for compressing RF samples with FLAC into .oga containers seems to be working reliably, and it would be convenient to be able to use the .raw.oga files directly with ld-decode without having to decompress them back to .raw or .lds first.

Perhaps a feature for rev5?

**Comment by simoninns** [comment]
Can this be closed @atsampson ?

**Comment by happycube** [comment]
Yup, it's implemented now.
