### ISSUE TITLE
ld-comb-ntsc 3D artifacts

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#126]
I've noticed in some black to other color transitions, there are blue and red dot artifacts.

Example:
![frame_ntsc_source_94](https://user-images.githubusercontent.com/44366267/51798829-22effe80-225c-11e9-90b5-326b6cfe949f.png)
![frame_ntsc_source_95](https://user-images.githubusercontent.com/44366267/51798830-23889500-225c-11e9-9895-cfae19b391a1.png)
![frame_ntsc_source_96](https://user-images.githubusercontent.com/44366267/51798831-23889500-225c-11e9-962c-8494cfc892c2.png)

3rd frame 3dcomb: 
![vlcsnap-2019-01-27-16h56m12s933](https://user-images.githubusercontent.com/44366267/51798835-3dc27300-225c-11e9-9516-24ed51297b0e.png)

2dcomb:
![vlcsnap-2019-01-27-16h56m28s677](https://user-images.githubusercontent.com/44366267/51798838-49ae3500-225c-11e9-9333-1721660bac56.png)

http://www.framecompare.com/image-compare/screenshotcomparison/1JFJNNNU

**Comment by Gamnn** [comment]
Example 2:
![frame_ntsc_source_2231](https://user-images.githubusercontent.com/44366267/52177402-a46b0200-2803-11e9-869f-5a204f075f2a.png)
![frame_ntsc_source_2232](https://user-images.githubusercontent.com/44366267/52177403-a46b0200-2803-11e9-8ec2-ceace7f5d561.png)
![frame_ntsc_source_2233](https://user-images.githubusercontent.com/44366267/52177404-a46b0200-2803-11e9-96b4-d477af0b5404.png)

3rd frame 3dcomb:
![vlcsnap-2019-02-03-22h30m58s725](https://user-images.githubusercontent.com/44366267/52177411-b351b480-2803-11e9-9c45-65474b282a63.png)

2dcomb:
![frame_ntsc_comb_2233_2d](https://user-images.githubusercontent.com/44366267/52177417-c5cbee00-2803-11e9-8c87-c98d38cd8070.png)

**Comment by Gamnn** [comment]
Example 3:

![frame_ntsc_source_29276](https://user-images.githubusercontent.com/44366267/52516470-36916100-2c6f-11e9-9b10-238c9eca8a18.png)
![frame_ntsc_source_29277](https://user-images.githubusercontent.com/44366267/52516471-36916100-2c6f-11e9-96c9-b9ebc7f7975c.png)
![frame_ntsc_source_29278](https://user-images.githubusercontent.com/44366267/52516472-36916100-2c6f-11e9-8fe9-e1024cf863a0.png)

3rd frame 3dcomb:
![vlcsnap-2019-02-09-13h30m04s341](https://user-images.githubusercontent.com/44366267/52516476-41e48c80-2c6f-11e9-896d-a7c6699173d5.png)

2dcomb:
![frame_ntsc_comb_29278_2dcomb](https://user-images.githubusercontent.com/44366267/52516477-4610aa00-2c6f-11e9-9a33-7ec644e3f716.png)

**Comment by happycube** [comment]
ntsc3d can't pick up the phone right now.
