### ISSUE TITLE
TBC file contained 1 less field than JSON metadata reported

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#130]
Decode command:

python3 ld-decode.py /media/sdi/Seagate\ Backup\ Plus\ Drive/SFTP/LDV4300D_2\ Captures/Apple\ Visual\ Almanac/Apple\ Visual\ Almanac_CAV_NTSC_side1_2018-11-26_13-12-45.lds /media/sdi/Seagate\ Backup\ Plus\ Drive/Rev4_Test/almanac --start 423 --length 850

Expected result 1700 fields in TBC and JSON
Actual result 1699 fields in TBC and 1700 in JSON

**Comment by happycube** [comment]
Unable to reproduce here.  .tbc file length was 813722000, which is exactly 1700 * (910 * 263 * 2) bytes.

**Comment by simoninns** [comment]
I just retested; and now I get the right result... I have a suspicion that it might have been caused by a mismatch of the ld-decode-tools shared library version on my dev machine :/  I'll close and reopen if I work out what went wrong.
