### ISSUE TITLE
NTSC/3D comb filter: Video Essentials Snell+Wilcox test is mostly processed as 2D CF.

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#133]
... it's effectively 2D comb filtering.  The -o option showed lots of movement in static areas.

temporary sample link: https://drive.google.com/open?id=1UYXWhgleD9o0juWL9j5BWiIbaDNFc2Gn

**Comment by atsampson** [comment]
I think I might have fixed this accidentally as part of #263.

Here's how the NTSC 3D output looked from rev4 until just before chromamerge:

![snellwilcox3d-output](https://user-images.githubusercontent.com/436317/60679956-7147a000-9e81-11e9-9f3e-6082c54934a4.png)

And here's how it looks now:

![snellwilcox3d-output](https://user-images.githubusercontent.com/436317/60679975-802e5280-9e81-11e9-89f9-466d5c1f42b6.png)

**Comment by simoninns** [comment]
Nice :)  I guess we should run some tests on it.  There is a motion map option which outputs the result of the flow detection I put in there; it's designed so you can see where the code thinks motion is occurring (like a heat-map).

**Comment by atsampson** [comment]
So no, I hadn't fixed it, I'd just broken it differently so it was always using the _other_ filter. Here's post-chroma-merge rev6 with `--oftest` (the blob is stationary here):

![3dmap2-output](https://user-images.githubusercontent.com/436317/60684547-33a14200-9e96-11e9-865f-6260753bee6e.png)

Trying different versions, they all have slightly different garbage at the bottom of the frame...

The reason for the garbage is that `OpticalFlow::convertYtoMat` returns a reference to a local -- `cv::Mat` doesn't copy the array you give it. Adding `.clone()` on the end puts it back to how it was in rev4 - it does detect the stationary blob, but it detects spurious movement too:

![3dmap2-output](https://user-images.githubusercontent.com/436317/60684498-f2109700-9e95-11e9-8c90-21f893d5a8e3.png)

**Comment by atsampson** [comment]
From a bit of fiddling, a couple of things that seemed to improve the motion detection:

- Subtracting 2 from `velocity` before the `qRound`, so very small movements were ignored.
- Only using one field of the input image. Currently it uses the interlaced frame, so horizontal edges of moving objects will have feathering that changes with the velocity.

I wonder if a much simpler motion detection approach would work better, though...

**Comment by happycube** [comment]
ntsc3d doesn't currently exist.
