### ISSUE TITLE
comb-* could use stdout output for pipelining

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#141]
For 'production' decodes it makes sense to write the output to stdout so that the large intermediate .rgb file isn't needed.

**Comment by simoninns** [comment]
Right now the ld-decode shared library provides random access to the input .tbc files (used by tools such as ld-analyse) - so making this sequential-only to support pipelines is a pretty major change.  Possible to do, but I wouldn't prioritise it for rev5.

**Comment by simoninns** [comment]
Both PAL and NTSC comb filters now support piped output
