### ISSUE TITLE
PAL Comb filter produces negative color if TBC file has separate fields

### ISSUE THREAD

**Issue by Zcooger** [happycube/ld-decode#145]
![obraz](https://user-images.githubusercontent.com/42012614/52401692-a44c5a00-2ac2-11e9-92e1-008ba66a02da.png)
![obraz](https://user-images.githubusercontent.com/42012614/52404211-b7fabf00-2ac8-11e9-809b-790399e84f94.png)
![virtualbox_pc 3_07_02_2019_11_59_21](https://user-images.githubusercontent.com/42012614/52407282-1d05e300-2ad0-11e9-97b1-b23396f6707d.png)
![virtualbox_pc 3_07_02_2019_11_59_29](https://user-images.githubusercontent.com/42012614/52407286-2000d380-2ad0-11e9-92a8-482fd4940de4.png)

PALDec software can process separate fields at once, but if they are combined negative colors appear. LDDecode can process color properly only on combined fields which normally never happens (unless it is a progressive 626 signal). Any chances for small fix? I have no idea how to correct this.

**Comment by simoninns** [comment]
I can't really understand what it is you are raising the issue about...  The comb filter is designed to accept field input, one field at a time and then produce frames by combining two fields.  In your report what do you mean by 'combined fields'?

**Comment by Zcooger** [comment]
LDS demodulation program produces a TBC file, that TBC file is been shown above in raw pixel viewer as 576 line frame.
Ok. I used old revision sample as you said. I was not aware of that honestly.
