### ISSUE TITLE
HELP: Windows build

### ISSUE THREAD

**Issue by neo7530** [happycube/ld-decode#147]
Has anyone compiled it for windows and can send me a download link?

Thanks anyways...

**Comment by simoninns** [comment]
There are no pre-compiled binaries available for the project at the moment (although we would welcome anyone to volunteer to perform package management).  Supported OS environment is Ubuntu 18.04 LTS - installation instructions are available on the project wiki.

If you'd really like windows OS support, you are welcome to open an issue requesting it.
