### ISSUE TITLE
ld-comb-ntsc/ld-comb-pal should output more toolchain-friendly dimensions

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#156]
Most video codecs and many tools want dimensions divisible by 4, 8, or 16.

Here's two possible dimensions to crop/pad to. I read that being divisible by 16 is ideal, but it will require considerable padding. Divisible by 8 should be fine too, and would only need two lines of padding.

Mod 8: 760x488 - Crop from line 40, col 132, pad 2 lines at bottom.
![mod8](https://user-images.githubusercontent.com/44366267/53169698-563a6900-3621-11e9-8f5e-892c46027a77.png)

Mod 16: 768x496 - Crop from line 40, col 128, pad 10 lines at bottom.
![mod16](https://user-images.githubusercontent.com/44366267/53169705-5b97b380-3621-11e9-9fc4-6c1d8a732138.png)

**Comment by Gamnn** [comment]
For reference, this is how it currently crops. Suggested ones above contain more potential information.

754x486 - Cropped from line 44 col 136, padded 4 lines at the top
![mod2](https://user-images.githubusercontent.com/44366267/53170102-93532b00-3622-11e9-8e40-2886b9380622.png)

**Comment by simoninns** [comment]
I guess this isn't NTSC specific?

**Comment by Gamnn** [comment]
The suggested dimensions and line to crop at are NTSC specific of course, but needing to be divisible by ideally 16 or 8 also applies to PAL. I don't have enough PAL material to check against.

**Comment by simoninns** [comment]
NTSC output dimension now 760x488, PAL output dimensions are now 928x576
