### ISSUE TITLE
Request for windows exe of  ld-comb-

### ISSUE THREAD

**Issue by Zcooger** [happycube/ld-decode#157]
Hello guys, I write this ticket to kindly ask for compilation of this tool for windows as cmd executable. Will it be possible? I encountered numerous problems when doing it as I'm not experienced with linux enough and terminal gcc usage. Thank you.

**Comment by neo7530** [comment]
I had it compiled for Windows, but it crashes while opening tbc files... Will give it a try tomorrow.

**Comment by neo7530** [comment]
Done… 
[ld-comb-pal.zip](https://github.com/happycube/ld-decode/files/2892998/ld-comb-pal.zip)

**Comment by simoninns** [comment]
Closing issue
