### ISSUE TITLE
PAL decode - misalignment of video lines

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#18]
There is some form of misalignment of the video lines in PAL decodes.  Please see the attached TBC output:

![tbcframe-14](https://user-images.githubusercontent.com/1068814/46578295-ea05f280-c9fc-11e8-8c84-0981ccc5a3c0.png)

**Comment by techmindorg** [comment]
happycube, we think this issue may have been introduced fairly recently - still-frame captures that Simon got from the Doomsday disc a while back don't have the horizontal field misalignment.

Are you using phase information from the chroma burst to fine-tune the TBC timing? (This is definitely a good idea in principle)
The chroma burst pattern looks "wrong" in the misaligned captures; when fields have been interleaved the chroma burst it should be a *fine* dot pattern. It may be that your program isn't anticipating the intricacies of the PAL chroma burst with its V-switch :-)  . Let me attach a couple of images to explain...

First image here is a crop from testcard F, this shows the WRONG burst alignment between fields.
![image](https://user-images.githubusercontent.com/43847426/46581291-08381680-ca2e-11e8-98fe-bad997868c4c.png)

Image below is a crop from the still-frames sequence Simon captured (with older code?) a while back, which shows correct (or much nearer correct) field-interleaved burst pattern.
![image](https://user-images.githubusercontent.com/43847426/46581338-a0360000-ca2e-11e8-9dee-2fdb2ea7382a.png)

I don't suspect they're doing anything special for LaserDisc. Do you have a copy of Rec.470 ? All the details will be in there.

**Comment by techmindorg** [comment]
(By the way, this won't be affecting my comb-filter/colour-decode as I'm treating the two fields completely independently.)

**Comment by simoninns** [comment]
There is a 'special' thing here just for PAL LaserDiscs called the video signal pilot burst; it's an additional synchronising pulse of 3.75MHz contained within the sync.  This is covered by IEC 60856-1986; here's the diagram of it from the specification:

![pal ld special burst](https://user-images.githubusercontent.com/1068814/46581427-e001e500-ca38-11e8-94e2-bf8d93870cf7.PNG)

From what @happycube mentioned to be earlier, it seems there is some issue with the code that locks on to that.  Nothing more to add really, but I thought it good to share the diagram with you @techmindorg

**Comment by techmindorg** [comment]
Cool!

**Comment by simoninns** [comment]
This looks fixed in the current commit - closing
