### ISSUE TITLE
DOC artifact

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#188]
The DOC seems to be getting the phase wrong on this dropout, causing an ugly artifact.

![frame_ntsc_comb_35645_doc](https://user-images.githubusercontent.com/44366267/57178026-9d589c00-6ea5-11e9-8317-67381a0a9a4c.png)
![frame_ntsc_comb_35645](https://user-images.githubusercontent.com/44366267/57178027-9df13280-6ea5-11e9-87a9-6eacf5052591.png)
![frame_ntsc_source_35645_doc](https://user-images.githubusercontent.com/44366267/57178028-9df13280-6ea5-11e9-8c24-ec0f0f92c197.png)
![frame_ntsc_source_35645](https://user-images.githubusercontent.com/44366267/57178029-9df13280-6ea5-11e9-9bcc-12dababc48af.png)

[docglitch.lds.zip](https://github.com/happycube/ld-decode/files/3144255/docglitch.lds.zip)

**Comment by Gamnn** [comment]
Possibly related to https://github.com/happycube/ld-decode/issues/104?

**Comment by simoninns** [comment]
Is the sample provided an NTSC disc with pull-down @Gamnn ?  If so, this isn't a bug - the DoC doesn't yet work correctly with pull-down discs (which is covered by #104) since the field order is moving (so correcting non-pulldown frames from pull-down frames causes phasing issues).

**Comment by Gamnn** [comment]
It wasn't properly mastered, so not proper pull-down, and the frame in question doesn't appear interlaced.
I didn't look too closely, but I wondered if it might still be the fault of the intrafield DOC that #104 might have a solution for.

**Comment by simoninns** [comment]
ok, I'm going to close this issue as it's probably already covered by #104 which will have to include an option to force intrafield DoC rather than the inter-field DoC used for non-pull down sources
