### ISSUE TITLE
PAL solid colour areas can have herringbone effects...

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#190]
This is observed on good disks such as Jason.

**Comment by happycube** [comment]
This is not a regression BTW, it is observed with rev4.  Still a serious bug.

**Comment by happycube** [comment]
Oops, I didn't know this was open when I made #230.

**Comment by simoninns** [comment]
With the newly repaired and calibrated LD-V4300D the sine-wave interference patterns are reduced on the Domesday discs (testing with set 1) - but still highly visible on National side 2 (which is CLV).  Here's frame 185 post comb-filter:

![frame_pal_comb_185](https://user-images.githubusercontent.com/1068814/59561452-d34e7b80-9020-11e9-9fc5-648932e05094.png)

**Comment by simoninns** [comment]
By way of experimentation I popped the Domesday AIV discs into a real Domesday system and took a look a the output; the wavy pattern is very obvious everywhere - so this is very likely an artefact of PAL discs common to all players which filter it well (like the LD-V4300D) or poorly (like the VP415).  Still not sure what actually causes it in the first place though.

**Comment by happycube** [comment]
I think we figured out that some of this was calibration related, and the rest just the properties of the disk...

**Comment by simoninns** [comment]
I'm still not convinced :)  But you can close the issue if you like.
