### ISSUE TITLE
Regression:  High # of spurious dropouts seen on some samples.

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#191]

**Comment by Gamnn** [comment]
This seems to be a display bug in ld-analyse, not properly flushing the dropouts between TBCs. Peeking at a 9777 frame rotter TBC first, then opening a second TBC 58742 I get something like this on the second:

![](https://i.imgur.com/YBXTgJa.png)


Quitting, then opening the second TBC on a fresh instance gives this:
![](https://i.imgur.com/5wFKZgb.png)

**Comment by simoninns** [comment]
Created an issue for the ld-analyse problem (as this is unrelated to the bug referenced by this issue) - issue #193

**Comment by simoninns** [comment]
Domesday National disc set 2 side 1 frame 1500-1600 show the spurious drop-out detection issue well (if you need a sample to look at @happycube )

**Comment by happycube** [comment]
Still investigating why, but the high frequencies on PAL demods before deemp are very high.  Last commit is a partial fix.

**Comment by simoninns** [comment]
Roger Rabbit PAL CAV bonus disc seems to be another.  Frames 80-90 to around 300.

**Comment by atsampson** [comment]
Another one: THX-1138 (PAL, TVL 002) side 2 frames 450-500, on brightly-coloured lettering. I've put a clip in sftp:adamsampson/Faults.

On the other hand, Pulp Fiction (NTSC, CC1423L) was suffering from this on neon signs (e.g. around side 1 frame 36560) back in September, but it's now decoding fine. I've put a clip of that there too.

**Comment by simoninns** [comment]
This issue is really old for a bug... is it still a bug or has it been fixed? @happycube

**Comment by happycube** [comment]
It should be better, but I'm not sure if it's *fixed*.

**Comment by simoninns** [comment]
I suggest we close this then and, if someone has a working example of what's still not fixed, open a new issue with the recreation steps included.
