### ISSUE TITLE
ld-analyse preview doesn't match ld-comb-ntsc output

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#192]
ld-analyse should be brought in-line with ld-comb-ntsc (and ld-comb-pal if also affected). At present, it still masks the top lines with black.

ld-comb-ntsc output:
![frame-0](https://user-images.githubusercontent.com/44366267/57196088-7200aa80-6f94-11e9-8e10-b24325a044e0.png)

ld-analyse save:
![frame_ntsc_comb_1](https://user-images.githubusercontent.com/44366267/57196121-bee48100-6f94-11e9-904d-7b5bd3faa5ec.png)

**Comment by simoninns** [comment]
Fixed
