### ISSUE TITLE
ld-combine-audio

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#197]
When #127 is re-implemented, an additional tool to combine analog audio .PCMs from multiple captures should be feasible with the same data.

**Comment by simoninns** [comment]
With so many good audio tools available already (such as audacity) - this can be easily solved in post.  So it probably doesn't require any priority right now (although having it automatic would be nice)

**Comment by simoninns** [comment]
Closing this and tracking #547 instead (which is a much more up-to-date request for the same thing)
