### ISSUE TITLE
ld-combine-efm (for digital audio)

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#198]
A utility to analyze and combine .EFMs from multiple captures would be useful both for data and digital audio.

**Comment by simoninns** [comment]
Probably going to be related to #207

**Comment by simoninns** [comment]
Splitting this into two issues (audio and data)

**Comment by simoninns** [comment]
This is a little out dated.  It should probably be raised as an enhancement for ld-disc-stacker.
