### ISSUE TITLE
Multiple dropouts on one line can cause DOD to mark good spots

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#205]
Seems to be the case more for longer dropouts, but having more than one on a line causes the DOD to mark a lot of the good portion between them.

[greedydod.lds.zip](https://github.com/happycube/ld-decode/files/3164419/greedydod.lds.zip)

![Screen Shot 2019-05-10 at 09 13 11](https://user-images.githubusercontent.com/44366267/57494925-9b0f9b00-7306-11e9-91f3-48a5499171d2.png)
![Screen Shot 2019-05-10 at 09 13 17](https://user-images.githubusercontent.com/44366267/57494924-9b0f9b00-7306-11e9-81ce-8afec942d0b8.png)

**Comment by happycube** [comment]
(note, may slip to rev6)

**Comment by happycube** [comment]
Put a cap on it's greedyness (which is quite useful in areas with long dropouts... cutting it completely causes visible false negatives).  I'll mark this done until/unless there's a nasty enough sample to re-evaluate my life^Wapproach.
