### ISSUE TITLE
Dropout in color back porch can cause misalignment

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#208]
![frame_ntsc_source_2](https://user-images.githubusercontent.com/44366267/57961977-cd944600-794d-11e9-9e7b-ac032c3664f7.png)

[misalign.lds.zip](https://github.com/happycube/ld-decode/files/3193450/misalign.lds.zip)

**Comment by happycube** [comment]
I think this is fixed now.  Same area as #217 so it'll get tested there
