### ISSUE TITLE
lddecode.py crash reporter missing

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#21]
Add a crash reporter to lddecode.py that outputs the typical information required for bug-fixing such as:

The current file name
The current frame number
Which part of the code crashed
Any relevant debug
The Python crash output text

The text should make it easy for testers to report errors (and there should be some text like: "Ensure you include the following information when raising issue reports")

**Comment by happycube** [comment]
Implemented a minimal bug report  (and made it so control-C exits cleanly)
