### ISSUE TITLE
Add PAL 3D comb filter support to ld-chroma-decoder

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#211]
The PAL comb filter is currently 2D only.  It would be good to add support for 3D comb filtering

**Comment by atsampson** [comment]
Worth noting the previous links about the BBC Transform PAL decoder in #9, including Jim Easterbrook's GPLv3 implementation.

**Comment by simoninns** [comment]
Updated issue title according to the rev6 naming

**Comment by happycube** [comment]
Does the transform decoder count for this, or should there be a non-transform 3D decoder as well?

**Comment by simoninns** [comment]
No idea.  My assumption was: issue open = issue not solved.  @atsampson - please close if issue closed or explain what issue is :)

**Comment by atsampson** [comment]
I'd say transform3d meets this requirement. I guess we could also implement an adaptive 3D PAL decoder that works like ntsc3d, but I'm not sure there'd be much point... at present I think the best thing we could do to improve PAL quality further is to figure out a way of doing automatic video equalisation so we could use the 1D demodulator by default with transform3d (i.e. the VITS work).
