### ISSUE TITLE
ld-analyse dropout analysis visual glitch

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#221]
When the .tbc has no dropouts, it causes a glitch in the dropout analysis chart window.

Ubuntu:
![Ubuntu](https://user-images.githubusercontent.com/44366267/58360654-ead49180-7ec4-11e9-8566-aed6b2d17a1c.png)

Mac:
![Mac](https://user-images.githubusercontent.com/44366267/58360658-ef00af00-7ec4-11e9-8cc1-81663f6eba2c.png)

**Comment by Gamnn** [comment]
New oddity, 0 is on the graph twice:

![Screen Shot 2019-06-02 at 09 45 49](https://user-images.githubusercontent.com/44366267/58755279-6bc20780-851b-11e9-9119-3b14bd965ba9.png)
![Screen Shot 2019-06-02 at 09 43 49](https://user-images.githubusercontent.com/44366267/58755280-6bc20780-851b-11e9-884b-f558c1235029.png)

**Comment by simoninns** [comment]
Fixed both issues and also fixed 'double zero' issue in the SNR graph too.
