### ISSUE TITLE
Domesday Community South weirdness

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#230]
One of Simon's copies has herringbone patterns similar to #206... and one of Ian's copies has some vroop in the middle.

The ~3 frame test samples should be very useful for comparing between captures and players, aside from the issues.

cs-simon1.lds has the most wavyness, simon2 has some as well but not nearly as bad.  The Ian samples seem more subdued... but ian 2 has a bit of vroop in the middle of every field.

**Comment by happycube** [comment]
Still see any of these weirdnesses with current rev6 and captures?

**Comment by simoninns** [comment]
Only the herringbone patterns.  I'll close this as #206 is open
