### ISSUE TITLE
ld-decode line timing verification

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#239]
There are instances where, due to disc defects mainly, the line moves out of position (vrooping(tm)) or timing is stretched to beyond what should be allowed by the specs.

It would be a nice enhancement if ld-decode's framing functions verified a line after the initial TBC and lowered the sync conf metadata value if something didn't look right.  This could be then used by ld-analyse to quickly locate problematic frames for manual correction (or identifying edge-case bugs).

**Comment by simoninns** [comment]
Related to #256

**Comment by happycube** [comment]
I think this is reasonably taken care of now...
