### ISSUE TITLE
PAL crash during decode of Domesday National side A (disc set 1)

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#246]
The following screenshot shows the crash output and the command line used for the decode:

![crashondecode2](https://user-images.githubusercontent.com/1068814/59610527-e2652480-9119-11e9-8d25-b4e52068211e.png)

The disc has edge rot causing major noise in the image.  This is the last frame saved by the JSON:

![frame_pal_source_37999](https://user-images.githubusercontent.com/1068814/59610603-032d7a00-911a-11e9-9109-4b44adc3d5a4.png)

**Comment by atsampson** [comment]
I'm seeing this with my not-very-good cx88 capture too. 3880b39f71cb3b56f310055412c7e5706501ec6d disabled the preceding test with `if False and ...` - should that have been re-enabled now?
