### ISSUE TITLE
PAL CAV with EFM causes 2dB decrease in SNR

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#248]
There is a clear correlation between the presence of EFM data and a 2dB drop in video signal quality (black level SNR) on all Domesday AIV discs.  The discs have sections with and without EFM data present.

For example; here is a partial decode of the EcoDisc side 1 which clearly shows the position of two sections of EFM (at the start and middle):

![eco1snr](https://user-images.githubusercontent.com/1068814/59651723-39efa880-918b-11e9-9118-68f158bbdf13.png)

This is in contrast to side 2 of the same disc which is CAV as well, but does not contain any EFM data (and maintains a better video quality overall with a smooth expected curve of gradually increasing quality):

![eco2snr](https://user-images.githubusercontent.com/1068814/59651784-8509bb80-918b-11e9-8755-0853a2c7e1c3.png)

The same issue can be seen on the DD community discs which contain no EFM during the intro video (there is a short burst of EFM from the first frame, then the video with analogue audio, then EFM again.  At the end is a tutorial video with no EFM and analogue audio):

![ddcom1snr](https://user-images.githubusercontent.com/1068814/59651862-c69a6680-918b-11e9-8642-95c650a9a93d.png)

The same pattern can be seen on side 2 of the disc (which is almost identical in structure, although suffers edge-rot causing a more gradual SNR change at the very end of the disc):

![ddcom2snr](https://user-images.githubusercontent.com/1068814/59651916-efbaf700-918b-11e9-8f6d-bf40b5b7c93c.png)

It looks very likely that this bug is causing Domesday discs to have lower video quality than is actually possible.

**Comment by simoninns** [comment]
By way of contrast and base-lining; here is the GGV1069 SNR (initial 15K frames) from the same capture setup

![ggvsnr](https://user-images.githubusercontent.com/1068814/59652157-cbabe580-918c-11e9-864c-02fe32d489b4.png)

**Comment by simoninns** [comment]
In case it's useful, here is a CSV of the VITS data from EcoDisc side 1:


[ecodisc_side1.tbc.zip](https://github.com/happycube/ld-decode/files/3299830/ecodisc_side1.tbc.zip)

**Comment by simoninns** [comment]
Relabelled as a question...  Is the drop due to some sort of bug (unlikely) or is it just the effect the presence of EFM has on the overall noise floor (likely)?

**Comment by happycube** [comment]
I think it's the effect on the noise floor.

**Comment by simoninns** [comment]
alrighty then... let's close it up :)
