### ISSUE TITLE
ld-cut.py docs

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#250]
Error when dddconv not available and no obvious place in the wiki to say where to get or how to install.
It was the first issue i hit when following the submitting a bug page.
https://github.com/happycube/ld-decode/wiki/Submitting-a-bug-report

Also no mention of the dddconv app in the following section:
https://www.domesday86.com/?page_id=1312#Getting_the_software

Command line:
 python3 ld-cut.py /media/ian/LDS/blackadder/BlackAdder4_CLV_PAL_side3_2019-06-17_19-48-41.lds /media/ian/LDS/blackadder/BlackAdder4_CLV_PAL_side3.cut.lds -s 3579 -l 10
Traceback (most recent call last):
  File "ld-cut.py", line 89, in <module>
    process = subprocess.Popen(['dddconv', '-o', outname, '-p'], stdin=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)3 ld-cut.py /media/ian/LDS/blackadder/BlackAdder4_CLV_PAL_si
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dddconv': 'dddconv'

**Comment by simoninns** [comment]
Install instructions are now included in the duplicator user-guide on domesday86.com
