### ISSUE TITLE
PAL crash during decode of Community North disc set 2

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#254]
Filename: Domesday Community_CAV_PAL_side1_North DS2_2019-06-14_21-55-19.lds
Seq. frame: 50559

Output:

![ddcommN_ds2crash](https://user-images.githubusercontent.com/1068814/59814237-db563600-9314-11e9-9fda-878b21b2bc20.png)

**Comment by happycube** [comment]
Somewhat fixed... it skips fields, but it should be possible to salvage them
