### ISSUE TITLE
PAL crash during decode of National side 1 - disc set 2

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#255]
Filename: Domesday National_CAV_PAL_side1_DS2_2019-06-14_19-14-06.lds

Seq Frame number: 48489

Output: 

![national_side1_ds2_crash](https://user-images.githubusercontent.com/1068814/59847044-c5bb2d80-9361-11e9-99f4-20b394c2b3d5.png)

**Comment by happycube** [comment]
Current version skips field (I think this was very similar to 256)
