### ISSUE TITLE
Sync confidence JSON parameter is (nearly always) 75%

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#256]
To allow both ld-analyse to flag potential problem-frames (and to enhance the functionality of ld-combine) it would be useful if the sync confidence parameter reflected the sync confidence of the attached field/frame.

**Comment by simoninns** [comment]
Related to #122

**Comment by happycube** [comment]
This should be better now - but is it good enough?

**Comment by simoninns** [comment]
I think this is fine for now; once the ld-combine side of things is up and running again, I will retest and open a new issue if required
