### ISSUE TITLE
PAL decode field ordering inconsistent 

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#258]
When decoding the same disc from two different captures, the PAL field ordering is inconsistent.

Decodes are the same disc, captured on two different players (DomesdayDuplicator1 and DomesdayDuplicator2 - both are LD-V4300Ds).

Command line for duplicator1:

![clidd1](https://user-images.githubusercontent.com/1068814/59972136-288f0d80-958a-11e9-8b94-b18b5ef8295c.png)

Command line for duplicator2:

![clidd2](https://user-images.githubusercontent.com/1068814/59972139-2fb61b80-958a-11e9-8e73-2185645a092f.png)

ld-analyse result for duplicator1:

![domedup1](https://user-images.githubusercontent.com/1068814/59972144-452b4580-958a-11e9-836c-5e2ddc4496d9.png)

ld-analyse result for duplicator2:

![domedup2](https://user-images.githubusercontent.com/1068814/59972148-4fe5da80-958a-11e9-8f35-ad2a578ba987.png)

Both discs are Domesday National Side 1 (disc set 2)

**Comment by skunge2000** [comment]
Could this be related to https://github.com/happycube/ld-decode/issues/257#issue-459481921

**Comment by simoninns** [comment]
Yes it could be; but I only found the regression this morning; so @happycube needs a little time to look into the cause (and in what commit it occurred since it might be very recent as I test with the on-going rev6 commits).

**Comment by simoninns** [comment]
The issue has been analysed and the fault seems to be within the ld-decode-tools shared library - the output from ld-decode is consistent between the decodes and the .tbc (and .json) are correct.  I need to look into the tools library and see why this issue is occurring.

**Comment by happycube** [comment]
On the ld-decode end, I just put up a block so that the .tbc file will only start with a first field (important for rev5.2, which will ship with rev5.1 tools)

**Comment by simoninns** [comment]
Issue appears to be a GUI error in ld-analyse which is transposing the VBI data into the wrong field:

![jsonanalysis](https://user-images.githubusercontent.com/1068814/59979588-12189e80-95ea-11e9-8f58-61b4cb0fe528.png)

**Comment by simoninns** [comment]
Cleaned up ld-analyse VBI handling and fixed bug that occurred in the shared-library that incorrectly reloaded certain metadata when a GUI application loaded a second file without restart.
