### ISSUE TITLE
Odd initialisation of b0-b6 in palcolour

### ISSUE THREAD

**Issue by atsampson** [happycube/ld-decode#262]
Spotted while reading through ld-comb-pal:

[This code](https://github.com/happycube/ld-decode/blob/ebf68032f3b9653c9a660749e8d21c414f181cae/tools/ld-comb-pal/palcolour.cpp#L179) and [this code](https://github.com/happycube/ld-decode/blob/ebf68032f3b9653c9a660749e8d21c414f181cae/tools/ld-comb-pal/palcolour.cpp#L189) in the current version of palcolour looks wrong. It's trying to initialise b0-b6 to point at the start of the surrounding lines for the burst detector and filter to read from - but the initialisation is in an unnecessary loop, and the final iteration of the loop will leave b0-b6 pointing to the *end* of the lines.

I think [this change](https://github.com/happycube/ld-decode/commit/336025488dc4f8843bf755bc18a37812e6d736a4#diff-ac694508165d1bb5aae44e06d02ea11fL174), which converted b0-b6 from arrays to pointers, left the loops behind by accident...

**Comment by simoninns** [comment]
Fixed in latest rev6 commit.
