### ISSUE TITLE
Merge 2D NTSC comb filter code with ld-comb-pal

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#263]
Since the 3D code is not functioning for NTSC and not present for PAL, it would be a good idea to merge the 2D comb-filters into a single code base (the 3D could then be added as a common function to both filters).  This would involve merging the 2D NTSC core filter into the PAL front-end (which is far more advanced than the current NTSC code and supports multithreading).

**Comment by simoninns** [comment]
Related issues #211, #133, #126, #123, #119, #104, #93

**Comment by atsampson** [comment]
This would also be a good opportunity for a more generic name -- ld-chroma-decoder? The current ld-comb-pal doesn't actually use a comb filter; it uses a pair of raised-cosine bandpass filters.

**Comment by simoninns** [comment]
This is very true; the name 'comb-filter' was due to the previous implementation and that it is a commonly accepted name for a chroma decoder in the NTSC universe.  I like the idea of renaming it to ld-chroma-decoder.

**Comment by simoninns** [comment]
Complete
