### ISSUE TITLE
ld-chroma-decoder should output yuv natively

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#283]
Rather than converting the output to RGB48, yuv444 would be preferable for most toolchains.
RGB could be left in as an option.

Piggybacking on this issue, an additional option to output with yuv4mpeg headers would be useful for piping into ffmpeg and other tools.

**Comment by simoninns** [comment]
YUV output - yes; specialisation of the output for ffmpeg; probably not.  As I said on IRC both metadata stream combination and 'prep' for ffmpeg would be better served by another tool.  It has nothing to do with chroma decoding.

**Comment by Gamnn** [comment]
#119 can be handled by downstream tools when this is implemented, as it will keep luma and chroma channels separate.

**Comment by atsampson** [comment]
Implemented in #618.
