### ISSUE TITLE
PAL decode VITs exceeding IRE range causing false DO detection

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#296]
Please see the screenshot.  The signal levels are high in the VITS causing the samples to clip and be interpreted as DOs (disc is jason side 4, but seen on the other discs too):

![jasonside4](https://user-images.githubusercontent.com/1068814/61281244-9d381f00-a7b9-11e9-9836-d591be77a398.png)

**Comment by happycube** [comment]
This is probably an MTF adjustment failure

**Comment by happycube** [comment]
Is this still an issue?

**Comment by simoninns** [comment]
probably not :)  It's so old, I'll close it and open a new one if the issue is observed.
