### ISSUE TITLE
Output pre-emphasis flag from ld-process-efm

### ISSUE THREAD

**Issue by atsampson** [happycube/ld-decode#306]
[As with CD audio](https://wiki.hydrogenaud.io/index.php?title=Pre-emphasis), some laserdiscs use pre-emphasis in their digital audio track. If the pre-emphasis flag is set, players need to apply a de-emphasis filter on playback (traditionally an analogue filter after the DAC).

ld-process-efm already stores the flag in `Section::QControl::isNoPreempNotPreemp`, which is false for disks using pre-emphasis. It would be useful if it could output this value so the user can tell whether to apply de-emphasis in later processing.

[SM078-3022](https://www.lddb.com/laserdisc/23405/SM078-3022/Talking-Heads:-Stop-Making-Sense) is an example of a disc that uses preemphasis. Here's a spectrum analysis of the song "Cities" as returned by ld-process-efm, as played back by an LD-V4400, and after deemphasis with sox's `deemph` effect:

![preemp3](https://user-images.githubusercontent.com/436317/62388528-6ef66580-b555-11e9-8af0-98d0402d0baa.png)

**Comment by simoninns** [comment]
Added "Total Pre-emp frames" counter to the "F2 Frames" tab - this tracks the number of valid sections processed that have the isNoPreemp flag set to false.  Not a perfect solution; but if this number is >0 it's likely the audio output required de-emp.

The ld-process-efm app will probably need a UI overhaul once ld-decode is working correctly with EFM (right now the GUI is designed to assist with testing and dev) - so a nicer solution should probably be implemented then.
