### ISSUE TITLE
NTSC 3D artefacts on shot changes

### ISSUE THREAD

**Issue by atsampson** [happycube/ld-decode#318]
The NTSC 3D decoder seems to produce incorrect output when the two fields it's looking at are significantly different.

For example, frame 115 of GGV1069 -- the middle frame in the crosstalk test -- should look like this, and does with ntsc2d:

![nr-vbar-output](https://user-images.githubusercontent.com/436317/63229944-22ba4f00-c1fe-11e9-871d-f5b206d37767.png)

But it looks like this with ntsc3d:

![nr-vbar-n3d-output](https://user-images.githubusercontent.com/436317/63229952-2d74e400-c1fe-11e9-912e-ec33ec95fdfa.png)

Patching Comb to always select the 3D decoder gives this:

![nr-vbar-n3d-output](https://user-images.githubusercontent.com/436317/63229966-61500980-c1fe-11e9-886d-fc071ad45bce.png)

I tried going back to rev4 and the 3D output is the same (we just weren't seeing it because the motion detection wasn't using it), so it doesn't look like a recent breakage.

**Comment by simoninns** [comment]
Moved to rev7 with the other 3D chroma-filter issues.

**Comment by happycube** [comment]
ntsc3d is de-implemented right now.  This will probably come back when it's re-implemented but it'll be different and another story... er, issue.
