### ISSUE TITLE
Some TBC and DOD failures

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#324]
Have some minor... would this be vroop? In any case, field misalignment on two frames from this sample.

```
file frame 530 CAV frame 517
file frame 531 CAV frame 518
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
file frame 532 CAV frame 519
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
file frame 533 CAV frame 520

```

![Screenshot from 2019-09-04 19-48-53](https://user-images.githubusercontent.com/44366267/64249056-c4a3a080-cf4d-11e9-9ba7-e45e4bb141b0.png)

```
file frame 2770 CAV frame 2757
file frame 2771 CAV frame 2758
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
file frame 2772 CAV frame 2759
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
file frame 2773 CAV frame 2760

```
![Screenshot from 2019-09-04 19-49-31](https://user-images.githubusercontent.com/44366267/64249149-f7e62f80-cf4d-11e9-9bda-7d70c4fc2e0a.png)

Additionally, the DOD is missing most of a lengthy dropout.

![Screenshot from 2019-09-04 19-48-33](https://user-images.githubusercontent.com/44366267/64249183-13e9d100-cf4e-11e9-8870-3e800dbf3efd.png)

Will PM the link for the .lds.

**Comment by simoninns** [comment]
Please retest and reopen if problem still occurs in latest rev6 commit.
