### ISSUE TITLE
LD-Analyse - Dropout Analysis Graph - Can zoom out too far

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#342]
Steps to reproduce:
Open Graph
Right hand click on chart area multiple times.
![image](https://user-images.githubusercontent.com/42521087/67676406-51c90b80-f979-11e9-9657-3d476b3fb631.png)

**Comment by simoninns** [comment]
This issue is caused by the Qt charts class, which is pretty poorly implemented.  There doesn't seem to be any way to reasonably catch the zoom out event and control the extent of it.  As a work-around, just click the 'Reset Zoom' button if you get lost.
