### ISSUE TITLE
Vroop - Hsync lost all throughout the disc except first 3k frames

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#343]
Same issue as #252 but further on in the same disc.

There is almost a H sync loss every few seconds throughout the entire disc after frame 3k
![image](https://user-images.githubusercontent.com/42521087/68046835-c337ef80-fcd4-11e9-8da9-7fdb423e90a7.png)

This is when looking at one of the sample files attached:
![image](https://user-images.githubusercontent.com/42521087/68046922-02664080-fcd5-11e9-97ac-9e2df5bcf54a.png)

This is one of the Minor Vroops
![image](https://user-images.githubusercontent.com/42521087/68046659-4c9af200-fcd4-11e9-8186-d353f97c78a7.png)

Have supplied a 100 frame sample in various locations across the disc. 
https://drive.google.com/drive/folders/1C5ajrO9LmxaDO5y-VSOs2VRznP2BcVrq

**Comment by simoninns** [comment]
@IanSmallshire  - was this and #252 resolved?  Can I close both issues?

**Comment by simoninns** [comment]
Wrong button :)

**Comment by IanSmallshire** [comment]
It is still an issue but have only found one disc affected. 
I have the other discs from BBC so will cap and retest other sides too.

**Comment by IanSmallshire** [comment]
Seems fixed after #218 fix
