### ISSUE TITLE
SNR Analysis Y axis numbers duplicated sometimes.

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#344]
Issue displayed here:
![image](https://user-images.githubusercontent.com/42521087/68526211-55da1f00-02d1-11ea-9a1d-da8fcc7ee229.png)

No issue on this one
![image](https://user-images.githubusercontent.com/42521087/68526286-07795000-02d2-11ea-9c75-0bc3b9bb619e.png)

I was originally thinking that they were 35 and then 35.5 etc on the first example with the decimal portion missing but 37 is not duplicated and the distribution of the grid lines is even

**Comment by simoninns** [comment]
Fixed; tick markers should only fall on whole numbers.
