### ISSUE TITLE
Line Scope is blank for line 625 on PAL

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#345]
![image](https://user-images.githubusercontent.com/42521087/68526320-7f477a80-02d2-11ea-8149-3eeefcaa148a.png)

but fine on line 624
![image](https://user-images.githubusercontent.com/42521087/68526335-99815880-02d2-11ea-9193-1cc5375af4b4.png)

**Comment by simoninns** [comment]
This doesn't look like a bug in ld-analyse - ld-analyse is grabbing the data and it's valid = the scan line is just zeros.   @happycube - can you confirm what ld-decode is passing in line 625?

**Comment by simoninns** [comment]
@happycube - still waiting for your feedback on this

**Comment by happycube** [comment]
I just need to remember to actually fix this.  Sometime next year ;)
