### ISSUE TITLE
IIR filter in FM demodulator?

### ISSUE THREAD

**Issue by techmindorg** [happycube/ld-decode#35]
Hi Chad,

Having been looking at the "oscilloscope" view of various colourbars and testcards, I've noticed that the rising edge of a white bar has a softer final-attack, and a harder initial-decay - see image.

Is there some kind of IIR (time-asymmetric) filter in your FM demodulator code, or is this likely an artifact of analogue processing in the source material / when the discs were mastered?

![image](https://user-images.githubusercontent.com/43847426/47191123-4e01b280-d33d-11e8-94c6-51765677d9b2.png)

**Comment by happycube** [comment]
Yes, there's an IIR - but it's really overly aggressive de-emphasis.  That should get taken care of with the other filtering (auto)adjustments.
