### ISSUE TITLE
PAL decoding failure (NPE disc)

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#36]
The following decode command:

python3 lddecode.py SFTP/Other/DVL909E_AIV_NORTH_POLE_CAV_FULL.lds ~/lddecode_out/NPE_DO_test2 --pal --start 270 --length 20000

Fails with the following error:

starting at  9322153531
status code 9150521
True None
624 312 313
frame  5555
1919
starting at  9322955406
CAV  5556
CAV  5556
False 5556
starting at  9323753553
True None
624 312 313
Traceback (most recent call last):
  File "lddecode.py", line 53, in <module>
    combined, audio, nextsample, fields = framer_ntsc.readframe(fd, nextsample, f == 0)
  File "/home/sdi/github/ld-decode/lddecode_core.py", line 1156, in readframe
    self.vbi = self.mergevbi(fields)
  File "/home/sdi/github/ld-decode/lddecode_core.py", line 1090, in mergevbi
    vbi_merged['framenr'] = vbi_merged['minutes'] * 60 * fps
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

Running against commit: 3af20e3fe681978edf85493e48161eec3754b740		branch 'master' of https://github.com/happycube/ld-decode

**Comment by happycube** [comment]
Probably fixed now, feel free to reopen of course...
