### ISSUE TITLE
EFM breaks on some discs

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#386]
EFM breaks on this set of LDs, with around 20% C1 error rate. The discs were formerly affected by hedgehogging ala #351, #325 et al. which may or may not be related.

sample: [okotowari.ldf](https://drive.google.com/open?id=1imZY5Jzq9xXgN-eJ0FCq615QtO3QVQg8)

**Comment by Gamnn** [comment]
Capped with a different player. and the section decodes fine. [Okotowari-919.ldf](https://drive.google.com/open?id=1CH1wZqFJMghK6ZAUJzfoXLVwTbqpu6CV)

However, the digital audio played on the first player, so I would assume it could still be decoded with some tuning.

**Comment by simoninns** [comment]
Were both players standard LD players?

**Comment by Gamnn** [comment]
first was HLD-X9, second DVL-919.

**Comment by simoninns** [comment]
Do we think this is a real issue, or more to do with the X9 being kinda broken?

**Comment by Gamnn** [comment]
I'd say it's a mix. The x9 decodes the audio in this section (mostly) fine, so ld-decode and tools should be able to as well.

**Comment by atsampson** [comment]
The filtered EFM waveform looks pretty horrible in both of those samples. (As do the VBI/VITS waveforms, but that's probably a different problem.)

919:
![okotowari-919](https://user-images.githubusercontent.com/436317/71635776-5af78280-2c1f-11ea-8b5c-2ceca01e0bed.png)

X9:
![okotowari-x9](https://user-images.githubusercontent.com/436317/71635780-6185fa00-2c1f-11ea-81f8-c6c2266ce6f4.png)

Adjusting the filter shape doesn't seem to improve the X9 sample much...

**Comment by simoninns** [comment]
Unless these test samples are coming from players that have been verified as calibrated (using GGV1069) I don't think it's really worth digging into as there are too many environmental variables to really understand what's going on.  If the EFM signal is bad, it's bad.  Marking as wontfix for now.

**Comment by simoninns** [comment]
Closing issue as wontfix
