### ISSUE TITLE
NTSC timing in TBC output frame incorrect

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#41]
The timing of the NTSC output frame from the TBC doesn't seem to be correct.  The frame is supposed to start (according to ld-decode rather than the video standard) at the end of the sync-tip:

- NTSC approximate timings:
- Horizontal blanking 10.90 us (consists of):
-- front-porch 1.50 us
-- sub-carrier burst 5.30 us (consists of):
--- sync-tip 4.70 us
--- breezeway 0.60 us
-- colour-burst 2.50 us
-- back-porch 1.60 us
- Active video 52.60 us

This should put the start of the active video line at 0.6 + 2.5 + 1.6uS from the beginning of the frame, but it's actually 0.6 + 2.5 + 1.6 + 0.4uS - and I have no idea where the extra .4uS is coming from.

Note: This isn't a problem for PAL frames where the timing appears correct.

**Comment by simoninns** [comment]
I looked at this a little more and it seems like the timing error is 0.6us (rather than 0.4)

**Comment by happycube** [comment]
There was an 8 pixel offset that was added for comb-ntsc compatiblity.  Removed it and adjusted comb-ntsc instead.
