### ISSUE TITLE
ld-decode VBI handling regression

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#414]
Decode command:

ld-decode /mnt/md0/SFTP/simoninns/LDV4300D_1\ Captures/Apple\ Visual\ Almanac/Apple\ Visual\ Almanac_CAV_NTSC_side1_DS1_2020-01-19_18-46-53.lds /mnt/md0/Decodes/almanac/almanacs1 --start 419

Leadout was 54004 (seq. frame) - last frame in TBC is 54005. (ld-analyse correctly shows the VBI as lead out flagged).

Final output from ld-decode:

file frame 54420 CAV frame 50683
file frame 54421 lead in
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
file frame 54422 lead in
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
WARNING:root:NTSC field phaseID sequence mismatch (player may be paused)
file frame 54423 CAV frame 50683
WARNING:root:Severe VSYNC-area corruption detected.
ERROR:root:Extreme VSYNC-area corruption detected, dropping field
ERROR:root:Unable to determine start of field - dropping field
ERROR:root:Unable to find any sync pulses, jumping one second
saving JSON and exiting

**Comment by happycube** [comment]
Fixed now.
