### ISSUE TITLE
--quiet no longer functional

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#427]
The change in logging seems to have broken the --quiet (-q) option in ld-chroma-decoder. This is probably a good time to see about adding it to ld-dropout-correct and any other tools that might be in a pipe as well.

**Comment by atsampson** [comment]
It'd be possible to move the option parsing into the library as well, so all the tools had the same set of logging options...

**Comment by simoninns** [comment]
Regression caused by fix for issue #410

**Comment by simoninns** [comment]
Added issue #429 for the suggestion by @atsampson as it's an enhancement.  For now I'll just fix the regression.

**Comment by simoninns** [comment]
Issue fixed
