### ISSUE TITLE
ld-diffdod segfault

### ISSUE THREAD

**Issue by mpownby** [happycube/ld-decode#445]
Found a segfault with ld-diffdod.

Steps to reproduce:

```
python3 ld-decode.py MACH3_DiscA_Pioneer_CracksAtBeginning_2020-01-19_19-26-59.ldf mack3_a_1000 -s 562 -l 1000 --noEFM
python3 ld-decode.py MACH3_DiscC_Pioneer_2020-01-19_21-20-52.ldf mack3_c_1000 -s 598 -l 1000 --noEFM
python3 ld-decode.py MACH3_DiscE_Scotch_VisibleRot_2020-01-19_22-16-00.ldf mack3_e_1000 -s 467 -l 1000 --noEFM
```

(this created the accidental situation of DiscA starting one frame before picture number 1 and ending on picture number 999)

```
ld-process-vbi mack3_a_1000.tbc
ld-process-vbi mack3_c_1000.tbc
ld-process-vbi mack3_e_1000.tbc

ld-discmap mack3_a_1000.tbc mack3_a_1000_mapped.tbc
ld-discmap mack3_c_1000.tbc mack3_c_1000_mapped.tbc
ld-discmap mack3_e_1000.tbc mack3_e_1000_mapped.tbc

ld-diffdod mack3_c_1000_mapped.tbc mack3_e_1000_mapped.tbc mack3_a_1000_mapped.tbc
```

Resulting output:
-----------------
developer@7cec531138bd:/8TB/MACH3$ ld-diffdod mack3_c_1000_mapped.tbc mack3_e_1000_mapped.tbc mack3_a_1000_mapped.tbc
Info: Processing 3 input TBC files:
Info:   Source #0: "mack3_c_1000_mapped.tbc"
Info:   Source #1: "mack3_e_1000_mapped.tbc"
Info:   Source #2: "mack3_a_1000_mapped.tbc"
Info: Using normal field order
Info: Dropout detection threshold is 400
Info: Not performing luma clip detection
Info:
Info: Loading TBC input source #0 - Filename: "mack3_c_1000_mapped.tbc"
Info: Processing input TBC JSON metadata...
Info: Video format is NTSC
Info: Determining input TBC disc type and VBI frame range...
Info: Disc type is CAV
Info: VBI frame number range is 1 to 1000
Info: Source has 0IRE at 18048 and 100IRE at 51200
Info: Loading input TBC video data...
Info: Loading TBC input source #1 - Filename: "mack3_e_1000_mapped.tbc"
Info: Processing input TBC JSON metadata...
Info: Video format is NTSC
Info: Determining input TBC disc type and VBI frame range...
Info: Disc type is CAV
Info: VBI frame number range is 1 to 1000
Info: Source has 0IRE at 18048 and 100IRE at 51200
Info: Loading input TBC video data...
Info: Loading TBC input source #2 - Filename: "mack3_a_1000_mapped.tbc"
Info: Processing input TBC JSON metadata...
Info: Video format is NTSC
Info: Determining input TBC disc type and VBI frame range...
Info: Disc type is CAV
Info: VBI frame number range is 1 to 999
Info: Source has 0IRE at 18048 and 100IRE at 51200
Info: Loading input TBC video data...
Info:
Info: Sources have VBI frame number range of 1 to 1000
Info:
Info: Verifying VBI frame multi-source availablity:
Info: Frame #1000 has only 2 source frames available - cannot correct
Info: Warning: 1 frame(s) cannot be corrected!
Info: Processing 1000 frames starting from VBI frame 1
Info: Processing VBI frame 1
Info: Processing VBI frame 100
Info: Processing VBI frame 200
Info: Processing VBI frame 300
Info: Processing VBI frame 400
Info: Processing VBI frame 500
Info: Processing VBI frame 600
Info: Processing VBI frame 700
Info: Processing VBI frame 800
Info: Processing VBI frame 900
Info: Processing VBI frame 1000
Info: Only 2 source frames are available - can not perform diffDOD for VBI frame 1000
Info: Only 2 source frames are available - can not perform diffDOD for VBI frame 1000
Segmentation fault (core dumped)

**Comment by simoninns** [comment]
Fixed
