### ISSUE TITLE
Vroop.

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#452]
VROOOOP!

![frame_ntsc_source_3](https://user-images.githubusercontent.com/44366267/73747466-d1495080-479a-11ea-80fa-9507fe38a29d.png)

[offsetvroop.zip](https://github.com/happycube/ld-decode/files/4153417/offsetvroop.zip)

This vroop also causes a desync in ld-discmap, which I'll open a separate issue for.

**Comment by Gamnn** [comment]
Slightly longer clip, and a clip from the same section from a capture that decodes normally.

[issue453-broke.zip](https://drive.google.com/open?id=1gRvWHyRD6X6q2Qp9ZrSP9U1rgXYkp044)
[issue453-notbroke.zip](https://drive.google.com/open?id=1-Gd5JZexgC-hYE8m3s5oncGwZp_QFUtR)

**Comment by happycube** [comment]
This is caused by a player skip.  Looking at the demodulated raw data there actually *is* an early VSYNC.

https://drive.google.com/open?id=1mkqJQzFHZjis7GZDic94WGevtJF5_L38

**Comment by Gamnn** [comment]
Not certain if ld-decode could handle player-induced problems any better, so closing for now.
