### ISSUE TITLE
Broken decode of NTSC CLV

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#46]
Whilst I was testing the VBI decoding functionality in ld-decode-tools I came across a very odd decode for one of my test files.  The source .lds is on the SFTP - here are the details (from my VBI testing notes):

Dead Man Walking - side 1 - NTSC CLV (chapter boundary)
00:20:28 - Chapter 3
00:20:32 - Chapter 4

python3 lddecode.py /SFTP/VBI_Test_Captures/Dead\ Man\ Walking_CLV_NTSC_side1_00H20M28S-00H20M32S_2018-11-06_09-31-30.lds ~/lddecode_out/Dead\ Man\ Walking_CLV_NTSC_side1_00H20M28S-00H20M32S_2018-11-06_09-31-30

Really odd decode of first 20 frames or so...

**Comment by happycube** [comment]
In this case the TBC is reacting to garbage data - it jumps to the next VSYNC in the middle of the field. 
 Talked it over on IRC - it's quite possible the player is still in pause at this point.  Closing for now, but there is an issue to fix...
