### ISSUE TITLE
Dropout Blues - False positive on the dropout detection.

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#471]
![image](https://user-images.githubusercontent.com/42521087/75757647-a9fa8a80-5d2a-11ea-9be5-827d09301a32.png)

![image](https://user-images.githubusercontent.com/42521087/75757621-9f3ff580-5d2a-11ea-9f4e-c2820b369442.png)

![image](https://user-images.githubusercontent.com/42521087/75757513-699b0c80-5d2a-11ea-9092-00499fb637e4.png)

![image](https://user-images.githubusercontent.com/42521087/75757545-7881bf00-5d2a-11ea-9ebf-bae3b0900f5d.png)

Four samples supplied here:
https://drive.google.com/open?id=1MQ5BFlAmXey_C2TYhc4qnm8l7phxvzPA

**Comment by happycube** [comment]
Found the check that caused this and disabled it... should be good now?

**Comment by IanSmallshire** [comment]
Will kick off decode of the full disc again and update

**Comment by IanSmallshire** [comment]
Much better than it was with almost perfect decode.
