### ISSUE TITLE
ld-lds-converter potential read/write beyond array bounds

### ISSUE THREAD

**Issue by coderjo** [happycube/ld-decode#477]
When converting a 16-bit file to a packed 10-bit file, if the input file is not an exact multiple of 8 bytes, the last iteration reads past the end of inputBuffer. Since outputBuffer::operator[] is used to assign to the output, it will properly resize as needed.

When unpacking a 10-bit file to a 16-bit file, if the input file is not an exact multiple of 5 bytes, inputBuffer is resized (but will have whatever garbage was already there), but the assignment into output will write past the end of the outputBuffer.

I can see two possible solutions:
1. error on an offending input stream
2. pad the input with 0s as needed to fill the last iteration

**Comment by simoninns** [comment]
Fixed
