### ISSUE TITLE
Warning from palencoder tool

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#483]
make -j8 all shows the following warning:

palencoder.cpp: In function ‘double syncPulseGate(double, double, SyncPulseType)’:
palencoder.cpp:288:28: warning: ‘length’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     return raisedCosineGate(t, startTime, startTime + length, 200.0e-9 / 2.0);
            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by atsampson** [comment]
No warning with current GCC or Clang, but that looks spurious anyway - the code immediately above either sets `length` or returns. For your compiler, does turning the "case NONE:" above into a "default:" make the warning go away?

**Comment by simoninns** [comment]
This was my environment it seems, sorry about that... a make distclean, qmake, make all - cleared the warning.
