### ISSUE TITLE
PAL field based output results in a crash

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#49]
Command to recreate:
sdi@sehotitan01:~/github/ld-decode$ python3 lddecode.py /media/sdi/Seagate\ Backup\ Plus\ Drive/SFTP/LDV4300D_2\ Captures/AIV/Domesday_DiscSet2/Domesday\ National_CAV_PAL_side1_Disc\ set\ 2_2018-10-02_18-14-36.lds ~/lddecode_out/DD_National_testcards --pal --start 1856 --length 20 --field

Result:
Namespace(MTF=1.0, MTF_offset=0.0, cut=False, end=-1, field=True, infile='/media/sdi/Seagate Backup Plus Drive/SFTP/LDV4300D_2 Captures/AIV/Domesday_DiscSet2/Domesday National_CAV_PAL_side1_Disc set 2_2018-10-02_18-14-36.lds', length=20, ntsc=False, outfile='/home/sdi/lddecode_out/DD_National_testcards', pal=True, seek=-1, start=1856)
Traceback (most recent call last):
  File "lddecode.py", line 121, in <module>
    picture, audio = field.downscale(linesout = linesout, lineoffset = lineoffset, final=True)
  File "/home/sdi/github/ld-decode/lddecode_core.py", line 1068, in downscale
    dsout, dsaudio = super(FieldPAL, self).downscale(lineoffset = 3, audio = final, *args, **kwargs)
TypeError: downscale() got multiple values for keyword argument 'lineoffset'

**Comment by happycube** [comment]
fixed
