### ISSUE TITLE
hsync dropout causes AGC blip

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#503]
Similar to #493, if there's an issue in the wrong spot, the AGC can get the brightness wrong in a frame. I am thinking AGC should be more temporally aware by default.

![frame_ntsc_source_6](https://user-images.githubusercontent.com/44366267/84678449-fd57b800-af6a-11ea-9a9d-4106d9a36671.png)

[agc_blip.ldf.zip](https://github.com/happycube/ld-decode/files/4781393/agc_blip.ldf.zip)

**Comment by Gamnn** [comment]
Another example.

[agc_blip2.ldf.zip](https://github.com/happycube/ld-decode/files/4782184/agc_blip2.ldf.zip)

**Comment by happycube** [comment]
I put in a very simple fix - using medians instead of means for each line, which should help.  I could do a bit more on this if needed though, so please test.

**Comment by happycube** [comment]
Now uses regular HSYNCs to compute sync/IRE0 AGC, so this should be much more robust.
