### ISSUE TITLE
hsync vroop

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#505]
Getting vroop in the hsync area on a couple of frames, perhaps triggered by a small dropout.
This causes the AGC to darken the frames in addition.

![frame_ntsc_source_3](https://user-images.githubusercontent.com/44366267/85237088-9e101100-b45e-11ea-8bba-0414efadb22a.png)
![frame_ntsc_source_4](https://user-images.githubusercontent.com/44366267/85237091-9fd9d480-b45e-11ea-925b-d7b5e5ec320a.png)
![frame_ntsc_source_5](https://user-images.githubusercontent.com/44366267/85237096-abc59680-b45e-11ea-80d4-2968b6f58dc2.png)

[vroopdark.zip](https://github.com/happycube/ld-decode/files/4810432/vroopdark.zip)

**Comment by Gamnn** [comment]
This might be related. There's a long dropout at the bottom of the previous frame like above. AGC brightens the frame but no vroop.

![frame_ntsc_source_5](https://user-images.githubusercontent.com/44366267/85247115-bc3e3700-b487-11ea-9302-7d89882ba6e2.png)
![frame_ntsc_source_6](https://user-images.githubusercontent.com/44366267/85247117-bcd6cd80-b487-11ea-8e6a-ac7dca83a3b6.png)

[glitchbright.zip](https://github.com/happycube/ld-decode/files/4811057/glitchbright.zip)

**Comment by happycube** [comment]
Should be fixed now...
