### ISSUE TITLE
VBI/VITS showing in decoded frame

### ISSUE THREAD

**Issue by toynbeeidea** [happycube/ld-decode#509]
> /home/erik/github/ld-decode/ld-decode AmonSaga-side2.ldf AmonSaga-side2 --noAGC -j -s 74

![amon-blep2](https://user-images.githubusercontent.com/16988667/86927185-03bbf880-c101-11ea-912a-92f43d0edf26.png)

I ran this segment through my old firewire capture setup:

![amon-blep](https://user-images.githubusercontent.com/16988667/86927172-ff8fdb00-c100-11ea-8e00-9458caeeb1cd.png)

So it seems like there's something here that plays normally, but ld-decode doesn't like.  Just for fun I tried running ld-discmap on it, but all that did was insert a blank frame after the glitch, making it worse.

ldf clip:  [https://drive.google.com/file/d/16um918jAYT1TG0WHafhM8mtjtcC9HjSR/view?usp=sharing](https://drive.google.com/file/d/16um918jAYT1TG0WHafhM8mtjtcC9HjSR/view?usp=sharing])

**Comment by Gamnn** [comment]
To be sure, have you tried re-capturing the RF?

**Comment by happycube** [comment]
I've looked at this just enough to know that my latest changes actually make this issue *worse* - it never syncs up again after this frame.  

I suspect the player might've lost tracking for a moment, but I haven't gotten far enough to confirm that either way.

**Comment by happycube** [comment]
OK I don't see any skips in the raw demodulation, so there's definitely a bug.  oops.

**Comment by toynbeeidea** [comment]
Oh dear - so my player goofed, then?  Huh.  Okay, I guess I'll go back and try a recapture, thanks for looking!

**Comment by happycube** [comment]
Reopening - the prob is current versions don't recover from this the way they ought to...

**Comment by atsampson** [comment]
I think I've just found another example of this - see `adamsampson/Faults/lain9-skip-fail.ldf` on the SFTP (from PILA-1500). There's a player skip at 00:24:10.23, 5 frames in, and after that the TBC locks to the wrong vertical position for several minutes:

![lain9-bad](https://user-images.githubusercontent.com/436317/87465520-b8c44880-c60c-11ea-9df7-813eabc3ab92.png)

(I've also put `andnow-skip-fail.ldf` in there, which is another player skip that current master handles fine but was causing problems back in May - I figure this might be useful if you're testing skip recovery...)

**Comment by happycube** [comment]
Committed a possible fix to branch "thereisnotry" (it was originally a cleanup branch :) ) - the failed frames in question are still vroopy, and before merging I'll add a small bit of detection/warning code.

**Comment by happycube** [comment]
Should be fixed now
