### ISSUE TITLE
 Encode without deinterlacing -add note abouf field order

### ISSUE THREAD

**Issue by oyvindln** [happycube/ld-decode#535]
As far as I know ffmpeg assumes bottom field first by default when encoding unless it's reading something that's flagged with field order. Video from capture devices and I think ld-decode typically ends up as top field first, so you will get some weird results when deinterlacing if its encoded the wrong way. There is a [```-top```](https://ffmpeg.org/ffmpeg.html#Advanced-Video-options) option for specifying the output field order manually, so I suggest adding this to the wiki part about encoding without deinterlacing.

@simoninns

**Comment by simoninns** [comment]
Thanks @oyvindln - I'll forward this to Stephen so he can review what needs changing on the wiki page:

https://github.com/happycube/ld-decode/wiki/Creating-video-from-PAL-decodes

**Comment by simoninns** [comment]
I've updated the page with the additional information.  Thanks for the help!
