### ISSUE TITLE
Clipping issues in Time Traveler

### ISSUE THREAD

**Issue by MooglyGuy** [happycube/ld-decode#540]
The currently-available LDF of Time Traveler has significant clipping issues; see (hear?) the attached WAV file for reference.

The LDF filename, for reference, is TimeTraveler_DiscA_Side1_2020-01-18_14-12-46.ldf
[time_traveler_audio.zip](https://github.com/happycube/ld-decode/files/5112013/time_traveler_audio.zip)

**Comment by happycube** [comment]
With the current levels it looks like it's at the edge so there might be slight clipping, can you test with the current main?

**Comment by happycube** [comment]
Just did a 30 second test at file frame 20K it spikes up pretty much to the edge but doesn't look clippy.  I'll close in a few days if i don't hear anything else.

**Comment by MooglyGuy** [comment]
I'll re-test sometime in the next day or two, please bear with me.

**Comment by simoninns** [comment]
Closing - inactive presumed fixed
