### ISSUE TITLE
Replace --WibbleRemover with a more descriptive switch

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#544]
'Wibble' isn't a term most people would understand.  Perhaps this should be --pal-band-stop or something more meaningful?

**Comment by Gamnn** [comment]
Perhaps documenting 'wibble' is the correct course here. --WibbleRemover is also used on the NTSC side of things, for distortion that looks the same as the PAL type, but the cause of the distortion and how it's mitigated is different.

**Comment by happycube** [comment]
I figured I'll just change the option name in ld-decode.  I'm still not sure what a professional-y name is for it though.  Neither version is NR in the traditional sense, but that's the result.

**Comment by simoninns** [comment]
iirc it's technically a notch filter?  so --notch-filter perhaps?

**Comment by happycube** [comment]
Fixed.  Using --V4300D_notch_filter and --NTSC_color_notch_filter
