### ISSUE TITLE
Implement drop out detection in ld-decode

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#55]
At the moment ld-dropout-detect is included as a shim for dropout detection.  ld-decode should perform the dropout detection instead and populate the JSON with the data.

**Comment by happycube** [comment]
Latest updates provide a first pass at this.

**Comment by simoninns** [comment]
I've removed ld-dropout-detect from the tool chain so we can focus testing on the new DOD instead.

**Comment by happycube** [comment]
I think one is still potentially useful as an adjunct, so do keep the code around :)

**Comment by happycube** [comment]
moved the start of processing down one line so it won't flag on the last bit of VSYNC.  I think it's Good Enough for now, but improvements will be ongoing.
