### ISSUE TITLE
ld-decode rev3 crashes with no --length specified

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#56]
Decode command:

python3 lddecode.py /media/sdi/Seagate\ Backup\ Plus\ Drive/SFTP/LDV4300D_2\ Captures/Apple\ Visual\ Almanac/Apple\ Visual\ Almanac_CAV_NTSC_side1_2018-11-26_13-12-45.lds /media/sdi/Seagate\ Backup\ Plus\ Drive/AlmanacDecode/almanac_side1 --start 418

Results in:

Namespace(MTF=1.0, MTF_offset=0.0, frame=False, infile='/media/sdi/Seagate Backup Plus Drive/SFTP/LDV4300D_2 Captures/Apple Visual Almanac/Apple Visual Almanac_CAV_NTSC_side1_2018-11-26_13-12-45.lds', length=None, ntsc=False, outfile='/media/sdi/Seagate Backup Plus Drive/AlmanacDecode/almanac_side1', pal=False, start=418)
Traceback (most recent call last):
  File "lddecode.py", line 68, in <module>
    for i in range(0, req_frames * 2):
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

(Note: Similar result if you do not specify --start)

**Comment by happycube** [comment]
Should be fixed now
