### ISSUE TITLE
Save as PNG enhancements in DD-Analyse GUI

### ISSUE THREAD

**Issue by Zcooger** [happycube/ld-decode#571]
This ticket is intended to suggest adding 16BPP monochrome PNG export function (in case comb filter is disabled) as well as batch export for selected range of frames for further custom toolchain processing.
If a comb filter is enabled it's possible to write RGB48 PNG files.

**Comment by simoninns** [comment]
This is possible using the existing tool chain.  You can run whatever frames you like through the comb filter and then convert the output into still frames.  There is (imho) no need for this to be implemented in ld-analyse.
