### ISSUE TITLE
Harmonize naming of ld-decode

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#58]
The ld-decode project uses a mixture of ld-decode (tools, repo name, directories) and lddecode (for the primary python executable); it would be nice if it all matched (i.e. use ld-decode throughout to keep things standard)

**Comment by happycube** [comment]
changed to ld-decode.py, will look at others later

**Comment by simoninns** [comment]
ld-decode.py is the primary issue since it's a command exposed to the user; I'd be happy if you closed the issue, but you are welcome to look generally at harmonising filenames too if you like :)

**Comment by simoninns** [comment]
Rev3 repo seems to contain two identical python files now, lddecode.py and ld-decode.py - shouldn't lddecode.py be removed?

**Comment by happycube** [comment]
Removed.
