### ISSUE TITLE
ld-analyse: SNR chart clips on stacked TBCs

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#581]
The current range of the SNR chart is probably fine for single captures, but on this stacked TBC, the white SNR peaks at 50.7db, which clips on the chart.

![snrclip](https://user-images.githubusercontent.com/44366267/101706977-9c4e0e80-3acd-11eb-9ff6-9395d1311c0a.png)

**Comment by simoninns** [comment]
Added fix in commit 90a8213; maxY is fixed at 48 (to ensure that the majority of graphs have the same scale) but it will increase if any data point is greater than 48 (to the value of the data point).

**Comment by simoninns** [comment]
Fixed in master
