### ISSUE TITLE
erase entire line on re'draw'

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#584]
simon: "Frame 2/2: File Frame 328: CAV Frame #1 ne Lead In" - what's a 'ne lead in'?  :smile:

This is because the new output code does \r, but doesn't pad the line output with spaces.

**Comment by simoninns** [comment]
Another comment on the command line output...  It would be good if the first and last frames were summarised on a separate line also - right now it's hard to see quickly if you started the decode at the correct point (when using --start).

Error messages are also now unclear; if you get an exception, there is no indication of what frame it occurred on:

Field phaseID sequence mismatch (7->2) (player may be paused)

Field phaseID sequence mismatch (2->1) (player may be paused)

Field phaseID sequence mismatch (1->6) (player may be paused)

Field phaseID sequence mismatch (6->3) (player may be paused)

Frame 36000/110000: File Frame 36344: CAV Frame #35999

**Comment by happycube** [comment]
Fixed
