### ISSUE TITLE
Current frame indicator for ld-analyse graphs

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#588]
It would make dropouts and irregularities in SNR easier to investigate if there was an indicator on the graphs of the frame you're currently looking at in the main window.

For example:

![indicator](https://user-images.githubusercontent.com/44366267/103213876-58268f00-4952-11eb-993a-cf762154700c.png)

**Comment by Gamnn** [comment]
It could also possibly act as a slider, to move the main window to the desired area.

**Comment by simoninns** [comment]
Needs some fairly complex enhancement to the graphs as you would also need to implement a zoom function (the red arrow in the example above is pointing to 54 fields containing the average shown).

**Comment by Gamnn** [comment]
Such enhancements would be great, but the indicator being more precise than the graph shouldn't matter for this. A slider/bar overlaid on the X axis going from 0 to number_of_fields should still show the area you're looking at.

**Comment by simoninns** [comment]
Fixed in master
