### ISSUE TITLE
ld-decode rev3 gets extremely slow as decoding progresses

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#60]
When testing rev3 decoding a 42K frame file, decoding get progressively slower as the decode continues.  Falling to over 1 second per field by about frame 40K.

The issue looks like it's related to the way the JSON output generates a temporary file; the file size (of the main JSON output) is around 16Mb by frame 40K.  ld-decode seems to write the whole thing as a .tmp and then copy it to the main .tbc.json causing a massive amount of file IO operations.

**Comment by happycube** [comment]
partial fix (leave this open) - after 100 fields it now writes every 1000.

**Comment by happycube** [comment]
Going to leave the partial fix in place for rev3.  Just don't interrupt it after decoding x999 frames and it won't be too bad. ;)

**Comment by simoninns** [comment]
This tests as fixed now; closing issue
