### ISSUE TITLE
Request for CVBS (Composite Video) Decoding 

### ISSUE THREAD

**Issue by titan-91** [happycube/ld-decode#617]
I'm working on testing ld-decode and its child project, vhs-decode. I can't contribute any code but can provide feedback and test results with different players. What would help with testing, and give a big boost to interest in the project in general, would be cvbs/composite video decoding. I understand this may be outside the scope of the project, but this would allow me and others to compare RF decoded results to hardware playback results, while still gaining the benefits of ld-decode's unmatched TBC, comb filter, and analysis tools such as ld-analyse. The code for processing and decoding cvbs signals is already here, and this would have endless applications. The traditional method of plugging in to a composite video output of the playback device would be used in this case, and capturing samples of the raw video waveform.

As far as I can tell, there is no official composite video software decoder available anywhere and people have been searching for one for years. It would be amazing if this could be implemented using the existing rate flags for 40MSPS, 35.8MSPS, and 28.6MSPS for the Domesday Duplicator and CXADC driver for the Conexant capture cards.

In terms of preservation, this could be used for more obscure formats such as CED and other formats with very expensive tape decks, such as Video 8 and Hi-8. Camcorders for these are the only economical option, and tapping the RF inputs from the heads directly is not feasible. Another application would be decoding of professional formats which require extremely expensive equipment to play back, such as U-Matic and Ampex D2 "Composite Digital" formats. Here's a video on that concept:

https://www.youtube.com/watch?v=cFacR9M6oXA

As far as implementation, I'm guessing it would be relatively straightforward. Instead of feeding the TBC code with demodulated composite video from a LaserDisc capture, just look for a command line argument flag and feed it the direct composite video signal from the input file, while performing DC level restoration and AGC of the signal. If there is interest in adding this feature, here's a .tar.gz archive file of some NTSC test patterns I've captured, at a rate of 28.6MSPS and 8 bits:

https://forum.videohelp.com/attachments/57098-1612232475/cvbs-samples.zip

**Comment by VideoMem** [comment]
That's interesting.

Maybe a separate cvbs-tbc-decode tool/script could be added to avoid adding more program switches to the main LD workflow.

**Comment by titan-91** [comment]
There's been some discussion on Discord about this, but not sure if anyone is working to implement it currently. Referencing issue #478 CVBS decoding can also help visualize filter differences and make other comparisons between RF and composite outputs for various players.

**Comment by skunge2000** [comment]
D2 (and the 1/2" equivalent D3) have either SDI or Parallel Rec 656-style 4fsc digital outputs available too - removing the need to capture analogue. (The SDI variant is quite rare - it's SMPTE 259 A for 14.32MHz NTSC and B for 17.72MHz PAL from memory - with the more regular 27MHz Rec 601 SMPTE 259 C?)

The PAL standard is documented here - but electrically the NTSC variant is the same : https://tech.ebu.ch/docs/tech/tech3280.pdf

**Comment by Gamnn** [comment]
#242 should help with interoperability for that.

**Comment by titan-91** [comment]
The vhs-decode fork has implemented composite decoding! I'm closing this request.

https://github.com/oyvindln/ld-decode

https://ready.cs.washington.edu/~tandersn/nobackup/cvbsdecoded.png
