### ISSUE TITLE
Faster LDF compression

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#624]
It can currently take hours to compress  .lds file to .ldf, since ffmpeg (which thus-far has given the best results) only has single-threaded flac encoding.

So, add to my wish list a multi-threaded flac compression tool.

Some notes on the currently used format:
```
container: ogg
format: signed 16bit little endian
channels: 1
sample rate: 40,000 Hz
```

It would also be a plus if it could add the checksum to the ogg container's metadata.

**Comment by ValZapod** [comment]
Yeah, see https://trac.ffmpeg.org/ticket/4638.

You can use flaCCL or FlaCuda though.

**Comment by TokugawaHeavyIndustries** [comment]
#719 takes advantage of FlaCCL and speeds up compression considerably
