### ISSUE TITLE
adding support for u16 file format.

### ISSUE THREAD

**Issue by tandersn** [happycube/ld-decode#626]
This is a feature request, per conversation on the discord site. 

Using 16 bit mode on CX card results in an unsigned 16 bit file.  For decoding, we have to run it through sox first to convert to s16.  Would be nice if there was u16 support natively. The default card crystal is more than adequate for 16 bit VHS RF capture and 16 bit CVBS capture. With my latest crystal mod of 54Mhz, i'm now in the realm of 16 bit LD RF capture too.

**Comment by happycube** [comment]
Thanks for reminding me - this should be in my next branch merge, but won't be tested.
