### ISSUE TITLE
PAL- Amplitude of Left and Right Analogue audio is different

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#651]
This is from a disc labelled as Mono.

Raw PCM 
![image](https://user-images.githubusercontent.com/42521087/126018510-f2b5f302-cc02-4549-a2f4-4738e1463b2a.png)

Causes the CX decoded audio to clip
![image](https://user-images.githubusercontent.com/42521087/126018518-32b039ac-188b-407e-b860-ba23c9b5f4ca.png)

**Comment by happycube** [comment]
![PAL GGV 1khz](https://user-images.githubusercontent.com/94856/130806856-36dea58f-2bf9-4428-b083-61821b83dadf.png)

I don't see a difference in PAL GGV, but I should cut amplitude by 3db.

**Comment by ValZapod** [comment]
In music it is possible to have even sound in only one channel or changing. This looks like music(?)

**Comment by happycube** [comment]
I did cut the amplitude, and since this appears to be a mono disk and the two channels are in pretty good sync on PAL GGV, I consider this PDO weirdness.
