### ISSUE TITLE
PAL - Dropouts outside possible range

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#654]
Tested over multiple samples

When plotting the extents of Start / End within a line and also the line numbers I have identified these:
- negative video line numbers for dropouts
- PAL + NTSC max dropout start is after max dropout end (thought they were cut at the end of a line)
- Without negative lines 0-313 is is 314 inclusive which is higher than 0-312 expected (625/2 = 312.5 rounded up for half line)

![image](https://user-images.githubusercontent.com/42521087/132942563-5a720bda-6846-4871-a6b1-3a51de43c837.png)

**Comment by happycube** [comment]
@oyvindln has a fixed version already, going to merge it into my current working branch and then merge it up:

https://github.com/oyvindln/ld-decode/blob/vhs_decode/vhsdecode/doc.py#L136

**Comment by happycube** [comment]
I merged above in a while ago, need to check to see if it's fixed.

**Comment by happycube** [comment]
Making another change to dropout detection - if I got it right, it'll block out any off-field dropouts from being seen at all.

**Comment by happycube** [comment]
(feel free to reopen if I *didn't* fix it)
