### ISSUE TITLE
ld-analyse:  comb filter button should be sticky...

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#67]
... it's kinda annoying having to press it after looking at different frames.

**Comment by simoninns** [comment]
I like the idea of this, but the filters are a bit too slow to process for interactive use in the GUI (when perma-on), which is why I implemented it as 'click to filter'.  I'll leave the issue open for now though; might be possible to implement it later.

**Comment by simoninns** [comment]
Moved to rev6 as it comes under speed up activities

**Comment by simoninns** [comment]
Moved to rev4 'cause @happycube needs it like Sméagol needs his gold ring.

**Comment by simoninns** [comment]
This also requires the video extent and drop-out highlighting to function over the comb-filtered frame.

**Comment by happycube** [comment]
Thanks for moving this up, it's very nice to have esp with the slider :)
