### ISSUE TITLE
decodeFaults has appeared in JSON with no explaination

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#675]
As per the title, it's not in the ld-decode metadata code nor is it in the wiki description.  It's either a bug and needs to be removed or the documentation needs updating (as well as the down-stream tools which will simply strip it out as-is).

**Comment by simoninns** [comment]
I've added this to the ld-decode-tools TBC metadata library, but the JSON format wiki needs updating.  Please update and then close the issue.

**Comment by happycube** [comment]
Documented bitfields, you might want to clean it up a bit.

**Comment by simoninns** [comment]
Good enough :)
