### ISSUE TITLE
Replace JsonWax with RapidJSON

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#684]
Rebuild the JSON metadata library functions using the RapidJSON library and use a SAX style interface to streamline the whole implementation.

**Comment by oyvindln** [comment]
If we go this route this could possibly allow us to limit the use of Qt to the gui parts of ld-decode-tools, unless there is something else than gui we're using from Qt that can't easily be swapped with standard library stuff (we're using qt int typedefs qvector qstring atm but I think that could mostly quickly be swapped with STL equivialents other than maybe unicode string/filename handling).
