### ISSUE TITLE
AC3 track leaking into left analogue audio.

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#697]
After decoding a short sample with AC3 and checking the analogue audio there is some data noise in the left channel.

Have tested against 2 discs. 
First sample has the AC3 Dolby digital and THX logo's and should be silent on the left analogue audio channel as it is an audio commentary and quite loud data can be heard.
The second sample i tested against is Terminator 2 Squeeze (Japan) and you cab barely hear the left audio which is the mono track from the film.

![image](https://user-images.githubusercontent.com/42521087/151655503-81374925-cf54-4f42-9995-53b32df3c36a.png)
 
Have supplied both samples on discord

**Comment by happycube** [comment]
I believe this is fixed now...
