### ISSUE TITLE
Update IRC link on wiki

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#703]
Link needs updating as there is still a Real IRC channel
[Freenode IRC channel](https://github.com/happycube/ld-decode/wiki/IRC-channel)

**Comment by simoninns** [comment]
I thought @happycube changed permissions on the wiki ages ago so it's editable provided you are logged into github?  @IanSmallshire have you tried simply updating it?

**Comment by IanSmallshire** [comment]
Have updated the wiki
