### ISSUE TITLE
ld-discmap audio output short by several seconds over a CAV disk

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#705]
PCM samples are disappearing from ld-discmap's output.  This was reported by TheMogMiner, and i confirmed it on TimeTraveler_DiscA_Side1_2020-01-18_14-12-46.ldf (which I believe is the file he's using)

original .tbc.json audioSamples adds up to 1798.0295 seconds, .pcm file length matches.

discmap'd .tbc.json adds up to 1797.99632 seconds (1 frame shorter), but the .pcm file only has 1794.56 seconds of data.

**Comment by simoninns** [comment]
Fixed in latest commit
