### ISSUE TITLE
Chroma Decoding broken in ld-analyse

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#707]
Using commit f40b68302cde42d03d737486776d9c18c11ef186 ( Feb 7, 2022) the colour is available in ld-analyse
Using the latest commit 7e6eac590c06b01ed1ca9aac88dd3b2bf734677c (Feb 25, 2022) the image is black when viewing chroma.

Old Commit
![image](https://user-images.githubusercontent.com/42521087/156059016-5de9aa3c-bbfb-4351-bccb-b45aac3dc0c0.png)
![image](https://user-images.githubusercontent.com/42521087/156059055-8ea2cece-5f78-4505-98a3-285f8f2273ea.png)

New version (showing chroma)
![image](https://user-images.githubusercontent.com/42521087/156059420-ec8345c7-b893-4462-9ee6-6d6de5414ab3.png)

**Comment by IanSmallshire** [comment]
Have checked it was broken on this commit 08f32a5782117dd5f3125b80219f7f01bf2f527e

**Comment by IanSmallshire** [comment]
Nothing showing up with starting ld-analyse -d for the debug options..
![image](https://user-images.githubusercontent.com/42521087/156061022-6e0292f8-8452-4774-b9af-9f66433bad87.png)

**Comment by atsampson** [comment]
@MooglyGuy, would you mind having a look at this? Probably missing initialisation in ld-analyse for your padding change - if you can't figure out what's wrong let me know and I'll have a look later.

**Comment by MooglyGuy** [comment]
Absolutely, I'll have a look at it this evening. I do apologize for the delay, work and life have been chaos.

**Comment by atsampson** [comment]
Don't worry, I know the feeling!

**Comment by IanSmallshire** [comment]
Confirmed fix, Cheers
