### ISSUE TITLE
ld-decode - Decoding ends on a clip for no reason - skipping problemsome frame allows processing to continue

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [happycube/ld-decode#713]
Clip starts at CLV 1520.  Few phase mismatches, and then at CLV 1536-ish, ld-decode stops processing.  Skipping a few frames by passing -s 14 (for this cut clip) skips over the spot with the issue and continues to continues to decode

[cut-test.zip](https://github.com/happycube/ld-decode/files/8406103/cut-test.zip)

**Comment by happycube** [comment]
Finally got around to this one - (sensibly) it turns out that during a skip the VSYNC IRE detection was very wrong, so it lost any ability to recover.
