### ISSUE TITLE
ld-chroma-decoder not finding json file

### ISSUE THREAD

**Issue by titan-91** [happycube/ld-decode#716]
When trying to run ld-chroma-decoder with the required tbc and json files present in the same directory after a decode, I am getting the below terminal output:

Critical: JSON wax library error: "No errors occured."
Critical: Opening JSON file failed: JSON file cannot be opened/does not exist
Info: Unable to open ld-decode metadata file

There are no spaces or special characters in the path or file names. Has there been a change or regression with JsonWax? Or is the utility getting confused by this returned "no errors occured" string?

From JsonWaxParser.h:

QString errorToString()
    {
        switch( LAST_ERROR)
        {
        case OK:                                        return "No errors occured.";
        case UNEXPECTED_CHARACTER:                      return "Unexpected character.";
        case EXPECTED_BOOLEAN_OR_NULL:                  return "Expected boolean or null.";
        case EXPECTED_COMMA_OR_END_BRACE:               return "Expected comma or closing curly bracket.";
        case EXPECTED_COMMA_OR_END_SQUARE_BRACKET:      return "Expected comma or closing square bracket.";
        case EXPECTED_STARTING_CURLY_OR_SQUARE_BRACKET: return "Expected opening curly or square bracket.";
        case SUDDEN_END_OF_DOCUMENT:                    return "Document ended unexpectedly.";
        case NOT_A_NUMBER:                              return "Not a number.";
        case CHARACTER_AFTER_END_OF_DOCUMENT:           return "Character after end of document.";
        case NOT_A_HEX_VALUE:                           return "Not a hexadecimal value.";
        case EXPECTED_QUOTE_OR_END_BRACE:               return "Expected quote or closing curly bracket.";
        case INVALID_STRING:                            return "Invalid string.";
        default:                                        return "";
        }
    }

**Comment by atsampson** [comment]
I've just built master, and the test suite passes happily, so I don't think anything's broken.

The error you're getting is what you see if it can't open the input files at all - are you sure it's being invoked with the right filename (e.g. it's not missing the `.tbc` or similar)?

**Comment by titan-91** [comment]
Yes, the command I'm using seems to be correct, unless something changed with the syntax. Screenshot attached.

![Screenshot from 2022-04-27 20-03-23](https://user-images.githubusercontent.com/69586484/165655980-25a1a703-e89f-42a7-8158-370b42f49ebd.png)
