### ISSUE TITLE
Remove videoParameters.fsc from JSON

### ISSUE THREAD

**Issue by atsampson** [happycube/ld-decode#726]
Currently the JSON `videoParameters` object contains a field called `fsc`: "The fSC in Hz, truncated to an integer".

The "truncated" part is important, because for both NTSC and PAL the true value has a fractional part. The few places in the tools where it's used expect it to be the correct value, so they're very slightly wrong at the moment - and for PAL this does actually make a small difference to the output.

Since the value of fSC is fixed for each video standard we support, I'm going to suggest that we:
- stop ld-decode from writing `fsc` at all, and remove it from the documentation
- make `VideoParameters::fsc` a double, rather than an integer, and rename it to `fSC`
- make the JSON parser ignore the fsc field if present, and set `fSC` exactly based on the video standard (as it does for `LineParameters` and other per-standard information)

I'd also like to make the audio and video `sampleRate` parameters doubles at the same time - in all but one place in the code they're used in a double context, and there's no reason why you couldn't have a non-integer sample rate.

The tools will still handle existing JSON files correctly after this change.

Any thoughts?

**Comment by simoninns** [comment]
I don't see any problem with this - looks logical. IIRC double wasn't supported by JSON which is why it wasn't used.  Has this changed?

We still have issue #242 to consider also... Not sure if that has meaning here since, currently, I don't think ld-decode is following the video standard (in a very technical sense)?

**Comment by simoninns** [comment]
Great; then it's an 'ok' from me - I think it's a good idea

**Comment by oyvindln** [comment]
Unless we need a custom fsc for some reason one could as well chose it from a constant based on the video standard and line count/sample rate, so it could maybe even be left out of the JSON entirely unless needed. (or optionally supplied as some string id in those cases.)

**Comment by atsampson** [comment]
See discussion in #727 - I'm now not sure that removing fSC makes sense until we've got a better story about how to support more than the existing two video standards.

**Comment by happycube** [comment]
Sounds good to me too.
