### ISSUE TITLE
Automatic MTF compensation

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#73]
This issue is to track the required improvements to ld-decode to handle automatic MTF compensation.  Technical details will be added soon.

**Comment by happycube** [comment]
I'm pulling this into rev4, but it may slip or be further refined in rev5.

**Comment by simoninns** [comment]
Pushed back into rev5 as discussed

**Comment by Gamnn** [comment]
here's an .lds with some false dropouts in the first 3 frames:

[MTF.lds.zip](https://github.com/happycube/ld-decode/files/3119974/MTF.lds.zip)

**Comment by happycube** [comment]
It's better than it was, but could be better.  Pushing into rev6.

**Comment by happycube** [comment]
Looking at a low-frame GGV sample, I'd say it's pretty accurate now (as of rev6)
