### ISSUE TITLE
Allow modification of NTSC format in metadata

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#744]
When an NTSC file is processed by ld-decode the metadata specifies if the format is NTSC-J or NTSC - however this is just a metadata difference (it changes the way the tools treat the input TBC).  Some NTSC-J discs (like StarRider) are not correctly labelled - so it would be useful to issue a command to flip the metadata between NTSC and NTSC-J.

Might be worth making a new tool such as 'ld-modify-metadata' which could capture other similar requirements as they are identified.

**Comment by atsampson** [comment]
This was fixed by #757.
