### ISSUE TITLE
ld-export-metadata: chapters to audacity labels

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#751]
It might be useful to have an option to export the chapters to an audacity labels file. e.g. for 'dual disc' discs with a CD-style soundtrack on the digital tracks.

**Comment by atsampson** [comment]
This should be easy enough - can you give an example of (or spec for) the format you want?

**Comment by Gamnn** [comment]
Here's some info:
https://manual.audacityteam.org/man/importing_and_exporting_labels.html

Basically it's a tab-separated file with start, end, and name.

Example output:
```
0.000000	11.590454	Chapter 0
11.590454	25.363425	Chapter 1
25.363425	48.941849	Chapter 2
48.941849	72.048198	Chapter 3
```
