### ISSUE TITLE
Chroma encoder documentation

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#759]
For both NTSC and PAL I don't see any documentation about the encoder in the wiki.  Either I can't find it or it's missing :)

**Comment by atsampson** [comment]
I've added a brief bit about it to the [tools page](https://github.com/happycube/ld-decode/wiki/ld-decode-tools).

**Comment by simoninns** [comment]
I've now split all the tools into individual pages including one for the chroma-encoder

**Comment by atsampson** [comment]
I'm going to say this one's done now - I don't think there's much more to say in the docs for ld-chroma-encoder.
