### ISSUE TITLE
ld-decode is really slow.

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#76]
I haven't done any performance tuning (multithreading, GPU FFT, etc) yet.  I'll get a round tuit(tm) eventually.

**Comment by happycube** [comment]
Some more bits:

- Python 3.7 via Anaconda is using multiple threads.  Low gain on intel, but a nice jump on AMD Bulldozer.

- Haswell (4th gen i) has AVX2 with FMA, which makes it ~~much faster~~ about half as slow vs earlier cores.

**Comment by happycube** [comment]
rev6 is now merely slow.  But there's probably more that can be done in rev7 :)

**Comment by simoninns** [comment]
This should be closed.  If required open a more specific issue for rev7 stating what will be sped up
