### ISSUE TITLE
Support for more Linux distros

### ISSUE THREAD

**Issue by lizardgai4** [happycube/ld-decode#769]
This will be a living document, updated as I try installing it on various Linux distros.

Here is much more detail: https://docs.google.com/document/d/132ycIMMNvdKvrNZSzbckXVEPQVLTnH_YX0Oh3lqtkkQ/edit?usp=drivesdk

**Comment by DreckSoft** [comment]
ld-decode actually works on my Manjaro. Just needed to change LIBS += -lqwt-qt5 to LIBS += -lqwt in ld-analyse.pro which is already mentioned in a commentary above that line.

Unfortunately I can't remember which packaged I did install.

**Comment by lizardgai4** [comment]
@DreckSoft
"Unfortunately I can't remember which packaged I did install."

That's okay.  I figure out which packages to install on each Linux distro, using the preferred package managers (Ubuntu has apt, Fedora has dnf, Manjaro has pacman, etc.)

**Comment by lizardgai4** [comment]
I am currently working on CMake files for ld-decode, and got ld-chroma-decoder to compile and give display the help screen.

**Comment by lizardgai4** [comment]
There is currently a pull request to have this project use CMake files, which work on nearly every Linux distro I tried (see the document link at the top for details).  Can we mark this as resolved just yet?

**Comment by atsampson** [comment]
If you put "Fixes #769." in the message for the PR, then this issue will be closed automatically when the PR is merged.

**Comment by lizardgai4** [comment]
@atsampson Got it, gave it that message
