### ISSUE TITLE
Remove samplesPerUs field from JSON

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#80]
Remove samplesPerUs from the JSON and use the sampleRate instead (as they are redundant)

**Comment by simoninns** [comment]
@happycube - the samplesPerUs field has been removed from the tools now and is not longer needed in the JSON output from ld-decode.  Can you remove it from ld-decode and then close this issue?

**Comment by simoninns** [comment]
Add blackLevelStart and blackLevelEnd to this list too... They are no longer processed by the tool's shared library and can be removed from the JSON output.  As per commit aa2f818

**Comment by happycube** [comment]
Fixed in rev4

**Comment by simoninns** [comment]
python3 ld-decode.py ~/lds/Domesday\ Community\ South_CAV_PAL_side2_Disc\ set\ 2_2018-10-02_17-21-20.lds ~/tbc/Domesday_CommS_2 --pal --start 295 --length 60000

Results in:

Namespace(MTF=1.0, MTF_offset=0.0, frame=False, infile='/home/sdi/lds/Domesday Community South_CAV_PAL_side2_Disc set 2_2018-10-02_17-21-20.lds', length=60000, ntsc=False, ntscj=False, outfile='/home/sdi/tbc/Domesday_CommS_2', pal=True, seek=-1, start=295)
Traceback (most recent call last):
  File "ld-decode.py", line 99, in <module>
    write_json(ldd, outname)
  File "ld-decode.py", line 79, in write_json
    jsondict = ldd.build_json(f)
  File "/home/sdi/github/ld-decode/lddecode_core.py", line 1353, in build_json
    spu = vp['samplesPerUs']
KeyError: 'samplesPerUs'

**Comment by happycube** [comment]
oops.  fixed.

**Comment by simoninns** [comment]
Confirmed
