### ISSUE TITLE
ld-decode crash on completion

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#83]
If ld-decode gets to the end of the .lds input file it crashes with the following message:

file frame 10630 CAV frame 22317
file frame 10631 CAV frame 22317
Traceback (most recent call last):
  File "ld-decode.py", line 78, in <module>
    f = ldd.readfield()
  File "/home/sdi/github/ld-decode/lddecode_core.py", line 1256, in readfield
    f, offset = self.decodefield()
  File "/home/sdi/github/ld-decode/lddecode_core.py", line 1225, in decodefield
    indata = self.freader(self.infile, self.readloc, self.readlen)
  File "/home/sdi/github/ld-decode/lddutils.py", line 213, in load_packed_data_4_40
    unpacked[0::4] = indata[0::5]

Since there is no way to specify 'decode the whole file' this crash will always happen when --length is longer than the file.  Really, if the user does not specify --length, the whole file should be decoded (at the moment it defaults to --length 1)

**Comment by simoninns** [comment]
This is partially fixed, if the --length isn't provided, ld-decode now decodes to the end of the file.  It's still outputing crash reports when no real crash happens though iirc

**Comment by happycube** [comment]
Should be properly fixed now
