### ISSUE TITLE
ld-decode hanging during decode

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#94]
output:

file frame 1778 CAV frame 1507
file frame 1779 CAV frame 1508
file frame 1780 CAV frame 1509
file frame 1781 CAV frame 1510
file frame 1782 CAV frame 1511
file frame 1783 CAV frame 1512
file frame 1784 CAV frame 1513
file frame 1785 CAV frame 21514

Then no progress...

Command line:
python3 ld-decode.py ~/lds/DVL909E_AIV_NORTH_POLE_CAV_FULL.lds ~/tbc/NorthPoleExpo_full --pal --start 271 --length 60000

**Comment by happycube** [comment]
This is rather amusing... with MTF adjustment on, it thinks it's looking at frame 21515, so it turns MTF off, and then it properly reads 1515, so it goes into an infinite loop.  Fixed by only allowing one change.
