### ISSUE TITLE
Comb filters produce 170Gb+ RGB files

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#97]
The use of RGB16-16-16 as an output format for the comb-filter is generating huge files (bigger than the original disc samples and .tbc files).

There should be options for both the PAL and NTSC comb filters allowing a more compact (as well as more 'standard') RGB output format.

**Comment by happycube** [comment]
What I've generally done is pipe comb filter output directly into ffmpeg to produce compressed video.

**Comment by simoninns** [comment]
I'm not proposing the removal of RGB16-16-16; but the addition of alternative output formats.

Pipelining is possible to reimplement with the new tool-chain, but not currently supported (as it's less useful for full disc decodes).

**Comment by happycube** [comment]
ah... to me, pipelining is *most* useful with full disk encodes.

**Comment by simoninns** [comment]
That, as they say, is a whole other issue report :)

**Comment by simoninns** [comment]
Both PAL and NTSC filters can now output directly to stdout avoiding the need to create a temporary file
